CARDS = [
['Marriage', 'Ezdevaaj', 'ازدواج']
['If You Don\'t Want To Be Shamed, Become The Colour Of Society', 'Khaahee Nashavee Rasvaa, Hamrang-e Jamaa-at Sho', 'خواهی نشوی رسوا همرنگ جماعت شو ']
['Infamous / Shamed', 'Rasvaa', 'رسوا']
['Crowd / The Masses', 'Jamaa-at', 'جماعت']
['Flowing', 'Ravaan', 'روان'],
['Permanent', 'Daaem', 'دائم'],
['Unless', 'Magar', 'مگر'],
['Salary', 'Hoghoogh', 'حقوق'],
['Architect', 'Me-maar', 'معمار'],
['Valley', 'Dareh', 'دره'],
['Side', 'Samt', 'سمت']
['Pencil Sharpener', 'Taraash', 'تراش'],
['To Sew', 'Dookhtan', 'دوختن'],
['Skirt', 'Daaman', 'دامن'],
['To Design', 'Tarh Kardan', 'طرح  کردن '],
['I Could', 'Tavaanestam', 'توانستم'],
['Trumpet', 'Sheypoor', 'شیپور'],
['Humiliation', 'Tahgheer', 'تحقیر'],
['Prostitute', 'Faahsheh', 'فاحشه']
['Forever', 'Taa Abad', 'تا ابد'],
['Peasant', 'Rayeat', 'رعیت'],
['Poverty', 'Faghr', 'فقر'],
['Criterion', 'Melaak', 'ملاک'],
['To Crush', 'Leh Kardan', 'له کردن'],
['Deer', 'Aahoo', 'آهو'],
['Social', 'Ejtamaayee', 'اجتماعی'],
['Direction', 'Jahat', 'جهت'],
['Severe', 'Shadeed', 'شدید'],
['(A) Show', 'Nemaayesh', 'نمایش'],
['Purple', 'Banafsh', 'بنفش'],
['Slow', ['Kond', 'Yavaash', 'Aahesteh'], ['کند', 'یواش', 'اهسته']],
['Interview', 'Mosaahebeh', 'مصاحبه'],
['Court', 'Daadgaah', 'دادگاه'],
['Outcome', 'Payaamad', 'پیامد'],
['Telescope', 'Doorbeen Nejoomee', 'دوربین نجومی'],
['Tulip', 'Laaleh', 'لاله'],
['Hurry', 'Ajaleh', 'عجله'],
['Temptation', 'Vasvaseh', 'وسوسه'],
['Dragonfly', 'Sanjaaghak', 'سنجاقک'],
['Match (Sport)', 'Mosaabegheh', 'مسابقه'],
['Result', 'Nateejeh', 'نتیجه'],
['Single (Relationship)', 'Mojarad', 'مجرد'],
['Too', 'Neez', 'نیز'],
['Season', 'Fasl', 'فصل'],
['Owner', 'Saaheb', 'صاحب'],
['Buggy', 'Kaaleskeh', 'کالسکه'],
['Primrose', 'Paamchaal', 'پامچال'],
['Daffodil', 'Narges', 'نرگس'],
['Musical Instrument', 'Saaz', 'ساز'],
['Pear', 'Golaabee', 'گلابی'],
['Sunset', 'Ghoroob', 'غروب'],
['To See Someone Off', 'Badregheh Kardan', 'بدرقه کردن'],
['Topic', 'Mozooh', 'موضوع'],
['Hanging', 'Aaveezaan', 'آویزان'],
['Unaware', 'Ghaafel', 'غافل'],
['Answer', ['Paasokh', 'Javaab'], ['پاسخ', 'جواب']],
['Dice', 'Taas', 'تاس'],
['Device', 'Vaseeleh', 'وسیله'],
['Recently', 'Taazehgee', 'تازهگی'],
['(Ice Cream) Cone', 'Gheef', 'قیف'],
['Silk', 'Abreesham', 'ابریشم'],
['Feather', 'Par', 'پر'],
['Horizontal', 'Ofoghee', 'افقی'],
['Vertical', 'Omoodee', 'عمودی'],
['Seashell', 'Sadaf', 'صدف'],
['To Move', 'Takoon Khordan', 'تکون خوردن'],
['I Hear', 'Man Meeshnavam', 'من می شنوم'],
['Pile', 'Toodeh', 'توده'],
['Close It (Command)', 'Beband', 'ببند'],
['Crime', 'Jorm', 'جرم'],
['Officer', 'Mamoor', 'مامور'],
['Farm', 'Mazraeh', 'مزرعه'],
['Doorman', 'Darbaan', 'دربان'],
['Astronaut', 'Fazaanavard', 'فضانورد'],
['Respectable', 'Mohtaram', 'محترم'],
['Passport', 'Gozarnaameh', 'گذرنامه'],
['President', 'Rayees-e Jomhoor', 'رئیس جمهور'],
['Bath', 'Vaan', 'وان'],
['Appetite', 'Eshtehaa', 'اشتها'],
['Calmly', 'Baa Khoonsardee', 'با خونسردی'],
['Exaggeration', 'Eghraagh', 'اغراق'],
['Penetrating Look', 'Negaahe Naafez', 'نگاه نافذ'],
['Shaky', 'Larzaan', 'لرزان'],
['Handkerchief', 'Dastmaal', 'دستمال'],
['To Wipe', 'Paak Kardan', 'پاک کردن'],
['Opinion', 'Agheedeh', 'عقیده'],




['Ordinary', 'Ma\'mool', 'معمولی'],
['Independence', 'Aastaghaalal', 'استقلال'],
['Warning', 'Ekhtar', 'اخطار'],
['Pregnant', 'Hameleh', 'حامله'],
['Recipe', 'Dastoorol Amal', 'دستور العمل'],
];
