CARDS = [
['Debtor', 'Bedehkaar', 'بدهکار'],
['Cottage', 'Kolbeh', 'کلبه'],
['To Plant', 'Kaashtan', 'کاشتن'],
['Field', 'Keshtzaar', 'کشتزار'],
['To Cultivate', 'Kesht Kardan', 'کشت کردن'],
['To Be Paid', 'Dastmozd Gereftan', 'دستمزد گرفتن'],
['To Provide', 'Faraaham Kardan', 'فراهم کردن'],
['To Feel', 'Hes Kardan', 'حس کردن'],
['Purpose / Intent', 'Manzoor', 'منظور'],
['Thank God', 'Shokr-e Khodaa', 'شکر خدا'],
['Glorious', 'Baashokooh', 'باشکوه'],
['Shame', ['Sharm', 'Khejaalat'], ['شرم', 'خجالت']],
['I Am Shy', 'Man Hejaalatee Hastam', 'من خجالتی هستم'],
['Happy', 'Shaad', 'شاد'],
['Alas', ['Afsoos', 'Hayf'], ['افسوس', 'حیف']],
['Hookah', 'Ghaliaian', 'قلیان'],
['To Take (Future He/She/It)', 'Bebarad', 'ببرد'],
['Tasteless / Boring', 'Beemazeh', 'بیمزه'],
['As Opposed To / Unlike', 'Bar Khalaaf-e', 'بر خلافِ'],
[['Furniture', 'Stuff'], 'Vasaayel', 'وسایل'],
['Easy', 'Aasaan', 'آسان'],
['Parents', 'Vaaledeyn', 'والدین'],
['Technology', 'Fanaavaree', 'فناوری'],
['Use', 'Estefaadeh', 'استفاده'],
['To Use', 'Estefaadeh Kardan', 'استفاده کردن'],
['I Am Teaching', 'Yaad Meedaham', 'یاد میدهم'],
['I Taught', 'Yaad Daadam', 'یاد دادم'],
['I Was Teaching', 'Yaad Meedaadam', 'یاد می دادم'],
['I Know', 'Man Meedaanam', 'من می دانم'],
['I Knew', 'Man Meedaanestam', 'من می دانستم'],
['Boring', 'Kesel Konandeh', 'کسل کننده'],
['Some (A Few)', 'Ba\'zee', 'بعضی'],
['Special / Specific', 'Khaas', 'خاص'],
['Special', 'Veezheh', 'ویژه'],
['Especially', 'Beh Veezheh', 'به ویژه'],
['To Waste', 'Talaf Kardan', 'تلف کردن'],
['Waste (Noun)', 'Etlaaf', 'اتلاف'],
['Waste Of Time', 'Etlaaf-e Vaght', 'اتلافِ وقت'],
['Waiting', 'Montazer', 'منتظر'],
['I Am Standing', 'Mee-eestam', 'می ایستم  '],
['I Am Waiting', 'Montazer Hastam', 'منتظر هستم'],
['Button', 'Dokmah', 'دکمه'],
['Pressure', 'Feshaar', 'فشار'],
['How (Formal)', 'Chegooneh', 'چگونه'],
['Use', 'Estefaadeh', 'استفاده'],
['Around The World', 'Beh Door-e Donyaa', 'به دورِ دنیا'],
['Ship', 'Kashti', 'کشتی'],
['I Started', 'Aaghaaz Kardam', 'آغاز کردم'],
['I Am Starting', 'Aaghaaz Meekonam', 'آغاز می کنم'],
['Distance', ['Faaseleh', 'Masaafat'], ['فاصله', 'مسافت']],
['Approximately', 'Hodood', 'حدود'],
['Rowing Boat', 'Ghaayegh-e Paarooyee', 'قایقِ پارویی'],
['Sailing Boat', 'Ghaayegh-e Baadbaanee', 'قایقِ بادبانی'],
['Route', 'Maseer', 'مسیر'],
['Companion', ['Hamsafar' / 'Hamraah'], ['همسفر', 'همراه']],
['Adventurous', 'Por Maajaraa', 'پرماجرا'],
['Incidents', 'Havaades', 'حوادث'],
['(Something) Happened', 'Etefaagh Aaftaad', 'اتفاق افتاد'],
['Crocodile', 'Temsaah', 'تمساح'],
['To Attack', 'Hamleh Kardan', 'حمله کردن'],
['I Was Hospitalised', 'Bastari Shodam', 'بستری شدم'],
['Power / Strength', 'Neeroo', 'نیرو'],
['Inevitably', 'Beh Naachaar', 'به ناچار'],
['Port (Sea)', 'Bandar', 'بندر'],
['Also', 'Hamcheneen', 'همچنین'],
['Portugal', 'Porteghaal', 'پرتغال'],
['Orange (Fruit)', 'Portaghaal', 'پرتقال'],
['The Remaining / The Rest', 'Bagheeyeh', 'بقیه'],
[['History (Subject)', 'Date'], 'Taareekh', 'تاریخ'],
['Indonesia', 'Andonezee', 'اندونزی'],
['Have Fun', 'Khosh Begzareh', 'خوش بگذره'],
['Discharged (Hospital)', 'Morakhas', 'مرخص'],

['To Travel A Distance', 'Tey Kardan', 'طی کردن'],
['To Pass (By / Through) (Challenging)', 'Oboor Kardan', 'عبور کردن'],
['To Start Moving (Somewhere)', 'Harekat Kardan', 'حرکت کردن'],

['I Passed', 'Gozashtam', 'گذشتم'],
['I Am Passing', 'Man Meegozaram', 'من میگذرم'],
['I Was Passing', 'Man Meegozashtam', 'من می گذشتم'],

['To Traverse (Road/Path)', 'Peymoodan', 'پیمودن'],
['I Traversed (Road/Path)', 'Man Peymoodam', 'من پیمودم'],
['I Was Traversing (Road/Path)', 'Man Meepeymoodam', 'من می پیمودم'],
['I Am Traversing (Road/Path)', 'Man Meepeymaayam', 'من می پیمایم'],

['To Continue', 'Edaameh Daadan', 'ادامه دادن'],
['I Am Continuing', 'Edaameh Meedaham', 'ادامه می دهم'],
['I Continued', 'Edaameh Daadam', 'ادامه دادم'],
['I Was Continuing', 'Edaameh Meedaadam', 'ادامه می دادم'],
];

//  ['', '', ''],
