CARDS = [
["Exciting", "Mohayyej", "مهیّج"],
['To Move (Around)', 'Takoon Khordan', 'تکون خوردن'],
['Humiliation', 'Tahgheer', 'تحقیر'],
['I Was Hospitalised', 'Bastari Shodam', 'بستری شدم'],
['Inevitably', 'Beh Naachaar', 'به ناچار'],
['To Provide', 'Faraaham Kardan', 'فراهم کردن'],
['To Wipe', 'Paak Kardan', 'پاک کردن'],
['Trust', 'Etemaad', 'اعتماد'],
['World', ['Aalam', 'Donyaa', 'Jahaan'], ['عالم', 'دنیا', 'جهان']],
['Stature', 'Ghaamat', 'قامت'],
['I Am Feeling', 'Ehsaas Meekonam', 'احساس می کنم'],
["Cost / Expense", "Hazeeneh", "هزینه"],
['Reluctantly', 'Baa Ekraah', 'با اکراه'],
['Caution', 'Ehteeaat', 'احتیاط'],
['Hapless', 'Beechaareh', 'بیچاره'],
['Ironing', 'Aatoo Keshee', 'اتو کشی'],
['Bucket', 'Satl', 'سطل'],
["Expensive", ["Por Hazeeneh", "Geraan"], ["پرهزینه", "گران"]],
['Shovel', 'Beelcheh', 'بیلچه'],
['Harmless', 'Beeaazaar', 'بیازار'],
['Castle', 'Ghal\'eh', 'قلعه'],
['Honesty', 'Sedaaghat', 'صداقت'],
['Annoying (Disturbance)', 'Mozaahem', 'مزاحم'],
['Ring (Shape)', 'Halgheh', 'حلقه'],
['Glass (Material)', 'Sheesheh', 'شیشه'],
['Frown', 'Akhm', 'اخم'],
['Beggar', 'Gedaa', 'گدا'],
['(A) Label', 'Eteeket', 'اتیکت'],
['Whole (Of)', 'Kol', 'کل'],
['Ass (Donkey)', 'Olaagh', 'الاغ'],
['Heel', 'Paashneh', 'پاشنه'],
['Immediately', ['Foree', 'Belaafaaseleh'], ['فوری', 'بلافاصله']],
['Immediate', 'Fooree', 'فوری'],
['Uniform', 'Roopoosh', 'روپوش'],
['Doormat', 'Paadaree', 'پادری'],
['Postage Stamp', 'Tamr Postee', 'تمبر پستی'],
['Rib', 'Dandeh', 'دنده'],
['Hall', 'Haal', 'هال'],
['Useless', 'Beefaaydeh', 'بیفایده'],
['Cabinet', 'Ghafaseh', 'قفسه'],
['Cage', 'Ghafas', 'قفس'],
['I Sent', 'Meeferestaadam', 'می فرستادم '],
['Bent / Crooked', 'Kaj', 'کج'],
['To Pay Lip Service', 'Lagh Lagh-e Zabaan', 'لق لق زبان'],
['Big Circular Drum', 'Daf', 'دف'],
['Revenge', 'Enteghaam', 'انتقام'],
['Sweetcorn', 'Zor-rat', 'ذرت'],
['Allergy', 'Hasaaseet', 'حساسیت'],
['I Hate', 'Motnaferam', 'متنفرم'],
['Weapon', 'Aslaheh', 'اسلحه'],
['Sofa', ['Mobl', 'Kaanaapeh'], ['مبل', 'کاناپه']],
['Heater', 'Bokhaaree', 'بخاری'],
['Mind your own business!', 'Boro pee kaaret', 'برو پی کارت'],
['Witch', 'Saahereh', 'ساحره'],
['Enthusiasm', 'Eshteeaagh', 'اشتیاق'],
['Rumbling (Stomach)', 'Ghaar O Ghoor', 'غار و غور'],
['Biting', 'Gazandeh', 'گزنده'],
['Algae', 'Jolbak', 'جلبک'],
['Seam / Slit', 'Darz', 'درز'],
['Sentence', 'Jomleh', 'جمله'],
['Goal (Purpose)', 'Hadaf', 'هدف'],
['To Guess', 'Hads Zadan', 'حدس زدن'],
['Nail (Hammer)', 'Meekh', 'میخ'],
['Lock (Key)', 'Ghofl', 'قفل'],
['Anger', 'Khashm', 'خشم'],
['Dizzy / Confused', 'Geej', 'گیج'],
['To Dare', 'Joraat Kardan', 'جرات کردن'],
['Homemade', 'Khaanegee', 'خانگی'],
['Oil (Not Cooking)', 'Naft', 'نفت'],
['Tea Glass', 'Estekaan', 'استکان'],
['Narrow / Slender', 'Baareek', 'باریک'],
['Economy', 'Eghtesaad', 'اقتصاد'],
['Cloth / Material', 'Paarcheh', 'پارچه'],
['I Am Hearing', 'Meeshnavam', 'می شنوم'],
['Future / Next', 'Aayandeh', 'آینده'],
['Next Month', 'Maah-e Aayandeh', 'ماه آینده'],
['Island', 'Jazeereh', 'جزیره'],
['Fan / Supporter', ['Tarafdaar', 'Havaadaar'], ['طرفدار', 'هوادار']],
['Barber', 'Salmaan', 'سلمان'],
['Calendar', 'Taghveem', 'تقویم'],
['Difficult', 'Doshvaar', 'دشوار'],
['Wine', 'Sharaab', 'شراب'],
['Stomach', ['Shekam', "Me'deh"], ['شکم', 'معده']],
['Salesman', 'Forooshandeh', 'فروشنده'],
['Lettuce', 'Kaahoo', 'کاهو'],
['Fluff', 'Kork', 'کرک'],
['I Had', 'Daashtam', 'داشتم'],
['Christian', 'Maseehee', 'مسیحی`'],
['Forbidden', 'Mamnooh', 'ممنوع'],
['Embassy', 'Sefaarat', 'سفارت'],
['Basket', 'Sabad', 'سبد'],
['Toothpaste', 'Khameer-e Dandaan', 'خمیر دندان'],
['Percentage', 'Dar Sad', 'در صد'],
['Cheery', 'Delgoshaa', 'دلگشا'],
['Greatness', 'Azamat', 'عظمت'],
['Ancient', 'Baastaan', 'باستان'],
['Location', 'Makaan', 'مکان'],
['Famous', ["Ma'roof", "Mash-hoor"], ['معروف', 'مشهور']],
['Abuse', 'Aazaar', 'آزار'],
['Race (People)', 'Nezhaad', 'نژاد'],
['Minority', 'Aghal-leeat', 'اقلیت'],
['Official (Thing)', 'Rasmee', 'رسمی'],
['Culture', 'Farhang', 'فرهنگ'],
['Dot / Point', 'Noghteh', 'نقطه'],
[['Tradition', 'Ceremony'], 'Rasm', 'رسم'],
[['Traditions', 'Ceremonies'], 'Rosoom', 'رسوم'],
['Because', 'Zeeraa', 'زیرا'],
['Equal', ['Mosaavee', 'Baraabar'], ['مُساوی', 'برابر']],
['I Am Welcoming', 'Esteghbaal Meekonam', 'استقبال میکنم'],
['I Am Shaving', 'Reesham Eslaah Mikonam', 'ریشم اصلاح می کنم',]
['Masterpiece', 'Shaahkaar', 'شاهکار'],
['Male (Animal)', 'Nar', 'نر'],
['Female (Animal)', 'Maadeh', 'ماده'],
['Faint', 'Ghash', 'غش'],
['To Weave', 'Baaftan', 'بافتن'],
['History (Track Record)', 'Saabagheh', 'سابقه'],
['Thin', 'Naazak', 'نازک'],
['Unfortunately', 'Motaasefaaneh', 'متاسفانه'],
['Silver', 'Noghreh', 'نقره'],
['Suggestion', 'Peeshnahaad', 'پیشنهاد'],
['French Fries', 'Seebzameenee Sorkh', 'سیب زمینی سرخ'],
['(Nightly) Rate', 'Nerkh', 'نرخ'],
['Certificate / Document', ['Sanad', 'Gavaahee'], ['سند', 'گواهی']],
[['Traffic Light', 'Indicator'], 'Cheraagh Raahnamaaee', 'چراغ راهنمایی'],
['Corridor', 'Raahro', 'راهرو'],
['Area', ['Mantagheh', 'Naaheeyeh'], ['منطقه', 'ناحیه']],
['I Am Searching', 'Meegardam', 'می گردم'],
['I Need', ['Neeaaz Daaram', 'Ehteeaaj Daaram'], ['احتیاج دارم', 'نیاز دارم']],
["I'm Sorry", "Motaa'asefam", 'متاسفم'],
['Fin', 'Baaleh', 'باله'],
['(A) Meeting', 'Jaleseh', 'جلسه'],
['To Invite', "Da'avat Kardan", 'دعوت کردن'],
['To Wash', 'Shostan', 'شستن'],
['Adabeeaat', 'Literature', 'ادبیات'],
['Value', 'Arzesh', 'ارزش'],
['Facilities', 'Emkaanaat', 'امکانات'],
['Study (Room)', "Otaagh-e Motaale'eh", 'اتاق مطالعه'],
['Radiator', 'Shofaazh', 'شوفاژ'],
['Storage', 'Anbaaree', 'انباری'],
['Carpet', ['Farsh', 'Ghaalee', 'Mooket'], ['فرش', 'قالی', 'موکت']],
['Fireplace', 'Shomeeneh', 'شومینه'],
['(To) Rent', 'Ejaareh', 'اجاره'],
['Consultant / Advisor', 'Moshaaver', 'مشاور'],
['Like (Similar To)', 'Maanand(e)', 'مانند'],
['On Foot', 'Peeaadeh', 'پیاده'],
['Middle', 'Vasat', 'وسط'],
['With Your Permission', 'Baa Ejaazeyeh Shomaa', 'با اجازه ی شما'],
['Witness', 'Shaahed', 'شاهد'],
['After An Hour', "Yeh Sa'at-e Digeh", 'یه ساعت دیگه'],
['To Punish', 'Tanbeeh Kardan', 'تنبیه کردن'],
['To Die', 'Fot Kardan', 'فوت کردن'],
['Suppository', 'Sheeaaf', 'شیاف'],
['High School', 'Dabeerestaan', 'دبیرستان'],
['Microscope', 'Zareh Been', 'ذره بین'],
['Body', ['Badan', 'Peykar', 'Tan'], ['بدن', 'پیکر', 'تن']],
['To Recommend', 'Tohsiyeh Kardan', 'توصیه کردن'],
['To Pay', 'Pardaakht Kardan', 'پرداخت کردن'],
['Pâtisserie', 'Ghanaadee', 'قنادی'],
['Knife', ['Chaaghoo', 'Kaard'], ['چاقو', 'کارد']],
['Student', ['Daaneshjoo', 'Shaagerd', 'Daanesh Aamooz'],  ['دانشجو', 'شاگرد', 'دانش آموز']],
['Capital (City)', 'Paayetakht', 'پایتخت'],
['Job', ['Shoghl', 'Kaar'], ['شغل', 'کار']],
['Tiger', 'Babr', 'ببر'],
['Triangle', 'Mosalas', 'مثلث'],
['To Plant', 'Kaashtan', 'کاشتن'],
['Shame', ['Sharm', 'Khejaalat'], ['شرم', 'خجالت']],
['Alas', ['Afsoos', 'Hayf'], ['افسوس', 'حیف']],
['As Opposed To / Unlike', 'Bar Khalaaf-e', 'بر خلافِ'],
['Easy', 'Aasaan', 'آسان'],
['Parents', 'Vaaledeyn', 'والدین'],
['Use', 'Estefaadeh', 'استفاده'],
['Distance', ['Faaseleh', 'Masaafat'], ['فاصله', 'مسافت']],
['Approximately', 'Hodood', 'حدود'],
['Route', 'Maseer', 'مسیر'],
['Incidents', 'Havaades', 'حوادث'],
['(Something) Happened', 'Etefaagh Aaftaad', 'اتفاق افتاد'],
['Indonesia', 'Andonezee', 'اندونزی'],
['Discharged (Hospital)', 'Morakhas', 'مرخص'],
['(An) Interest', 'Alaagheh', 'علاقه'],
['Style (of)', 'Sabk(e)', 'سبکِ'],
['Skilled', 'Maaher', 'ماهر'],
['Actor', ['Baazeegar', 'Honarpeesheh'], ['بازیگر', 'هنرپیشه']],
['Almost', 'Taghreeban', 'تقریباً'],
['Last Year', ['Saal-e Gozashteh', 'Paar Saal'], ['سال گذشته', 'پارسال']],
['Tourist', 'Gardeshgar', 'گردشگر'],
['Tourism', 'Gardeshgaree', 'گردشگری'],
['Is Counted As', 'Beh Hesaab Meeaaeed', 'به حساب می آید'],
['To Record', 'Zabt Kardan', 'ضبط کردن'],
['I Visited', 'Deedan Kardam', 'دیدن کردم'],
['I Got Out Of Bed', 'Boland Shodam', 'بلند شدم'],
['Except For', 'Beh Joz', 'به جز'],
['Some (Measurable)', 'Meghdaari', 'مقداری'],
['To Tidy', 'Morat-tab Kardan', 'مرتّب کردن'],
["Untidy", "Naamorat-tab", "نامرتّبه"],
['Get (Something) Ready / Prepare', 'Aamaadeh Kardan', 'آماده کردن'],
['I Am Cooking', 'Meepazam', 'می پزم'],
['I Cooked', 'Pokhtam', 'پختم'],
['While / During', ['Hengaam(e)', 'Dar Haal(e)'], ['هنگام', 'در حالی']],
['(A) Paw', 'Panjeh', 'پنجه'],
['Power / Strength', 'Neeroo', ['نیرو']],
['(An) Ability', 'Tavaan', 'توان'],
['(A) Wound', 'Zakhm', 'زخم'],
['Similar', 'Shabeeh', 'شبیه'],
['Rough (Coarse)', 'Zebr', 'زبر'],
['Yap / Howl (Dog)', 'Zoozeh', 'زوزه'],
['Snail', 'Halazoon', 'حلزون'],
['Nest', 'Laaneh', 'لانه'],
['Corner', 'Goosheh', 'گوشه'],
['Fox', 'Roobaah', 'روباه'],
['Farmer', ['Keshaavarz', 'Dehghaan'], ['کشاورز', 'دهقان']],
['To Separate', 'Jodaa Shodan', 'جدا شدن'],
['Profession', 'Herfeh', 'حرفه'],
['Career', 'Kaar-e Herfeh', 'کارِ حرفه'],
['To Adjust', 'Vafgh Daadan', 'وفق دادن'],
['Preference', 'Tarjeeh', 'ترجیح'],
['Education', 'Tahseelaat', 'تحصیلات'],
['Ambience', 'Safaa', 'صفا'],
['Compulsory', 'Ejbaar', 'اجبار'],
['Sand', 'Maaseh', 'ماسه'],
['Faith', 'Eemaan', 'ایمان'],
['Person', ['Aadam', 'Nafar', 'Fard'], ['آدم', 'نفر', 'فرد']],
['Warning', 'Ekhtaar', 'اخطار'],
['Hookah', 'Ghaliaan', 'قلیان'],
['Pregnant', 'Haameleh', 'حامله'],
['Recipe', 'Dastoorolamal', 'دستورالعمل'],
['Independence', 'Esteghlaal', 'استقلال'],
['(The) Effects', 'Aasaar', 'آثار'],
["Bankrupt", "Varshekasteh", "ورشکسته"],
["Tax", "Maaleeaad", "مالیات"],
["According To / On The Basis Of", "Bar Asaas-e", "بر اساسِ"],
["Rumour", "Shaaye-eh", "شایعه"],
["Rumours", "Shaaye-aat", "شایعات"],
["Family Man", "Khaanevaadeh Doost", "خانواده دوست"],
['Now', ['Haalaa', 'Aknoon'], ['حالا','اکنون']],
["Charity", "Kheyreeyeh", "خیریّه"],
["Keeping / Looking After", "Negahdaaree", "نگهداری"],
[["I Took", "I Won"], "Man Bordam", "من بردم"],
[["I Am Taking", "I Am Winning"], "Man Meebaram", "من می برم"],
["Role", "Naghsh", "نقش"],
["To Manage (Something)", "Edaareh Kardan", "اداره کردن"],
["Nuts", "Aajeel", "آجیل"],
["Each Other", "Hamdeegar", "همدیگر"],
["Housemate", "Hamkhaaneh", "هم خانه"],
["3rd Time", "Seh Martabeh", "سه مرتبه"],
["Firework", "Aatish Baazi", "آتش بازی"],
["Statue", "Mojasameh", "مجسمه"],
["Captain", "Kaapeetaan", "کاپیتان"],
["My Turn", "Nobat-e Man", "نوبتِ من"],
["Free Time", "Vaght-e Aazaad", "وقت آزاد"],
['For This Reason', ['Be hameen daleel', 'Beh Hameen El-lat'], ['به همین دلیل', 'به همین علّت']],
["Meticulous / Pernickety", "Vasvaasee", "وسواسی"],
["In Addition", "Dar Zemn", "در ضمن"],
['For Example', ['Masalan', 'Baraaye Mesaal', 'Baraaye Nemooneh'], ['مثلا', 'برای مثال', 'برای نمونه']],
["Can (Drink)", "Ghootee", "قوطی"],
["Fizzy Drink", "Nooshaabeh", "نوشابه"],
["To Throw Away", "Door Andaakhtan", "دور انداختن"],
["Pair / Couple / Even", "Z-oh-j", "زوج"],
["To Watch", "Tamaashaa Kardan", "تماشا کردن"],
["Secluded", "Khalvat", "خلوت"],
["Home Cooking", "Dast Pokht", "دست پخت"],
["Available / Present", "Mojood", "موجود"],
["Vegetarian", "Geeyaahkhaar", "گیاه خوار"],
["(A) Plant", "Geeyaah", "گیاه"],
["To Fish", "Maahee Gereftan", "ماهی گرفتن"],
["Normal / Ordinary", "Ma'mool", "معمول"],
["Unusual", "Gheyr-e Ma'mool", "غیرِ معمول"],
['Free', ['Raayegaan', 'Majaanee'], ['رایگان', 'مجانی']],
['Different', ['Mokhtalef', 'Motefaavet'], ['مختلف', 'متفاوت']],
["Definitely", "Motma-en-nan", "مطمئناً"],
["(A) Hook", "Gholaab", "قلّاب"],
["How Come?", ["Chetoor Mageh?", "Chetoor Magar?"], ["چطور مگه", "چطور مگر"]],
["Delicious", "Lazeez", "لذیذ"],
["Right There", "Hamoonjaa", "همونجا"],
["In This Case / In This Way", "Beh Een Soorat", "به این صورت"],
["To Chat", "Gap Zadan", "گپ زدن"],
["Club (e.g Sports)", "Baashgaah", "باشگاه"],
['Running', ['Daveedan', 'Do'], ['دویدن', 'دو']],
["(A) Runner", "Davandeh", "دونده"],
['Match / Competition (Sport)', 'Mosaabegheh', 'مسابقه'],
["Teenager", "Nojavaan", "نوجوان"],
["Coach / Trainer", "Morabbi", "مربّی"],
["Speed", "Sor-at", "سرعت"],
["Champion", "Ghahremaan", "قهرمان"],
["To Operate On (Surgery)", "Amal Kardan", "عمل کردن"],
['Never', ['Hargez', 'Heechgaah'], ['هرگز', 'هیچ گاه']],
["Excitement", "Hayejaan", "هیجان"],
["Athletics", "Meydaanee", "میدانی"],
["Vet", "Daampezeshk", "دامپزشک"],
["Zoo", ["Paark-e Vahsh", "Baagh-e Vahsh"], ["پارکِ وحش", "باغِ وحش"]],
["Beast / Monster", "Vahsh", "وحش"],
["To Insist", "Esraar Kardan", "اصرار کردن"],
["To Accept", "Ghabool Kardan", "قبول کردن"],
['Beginning', ['Aaghaaz', 'Ebtedaa'], ['آغاز', 'ابتدا']],
["Section", ["Bakhsh", "Ghesmat"], ["بخش", "قسمت"]],
["Domestic / Tame", "Ahlee", "اهلی"],
["Mammoth", "Maamoot", "ماموت"],
["To Escape", "Faraar Kardan", "فرار کردن"],
["Documentary", "Feelm-e Mostanad", "فیلم مستند"],
["Porch", "Ayvaan", "ایوان"],
["Surgeon", "Jarraah", "جرّاح"],
["Types (Of)", "Anvaah", "انواعِ"],
["To Treat / Cure", "Darmaan Kardan", "درمان کردن"],
["(The) News", "Akhbaar", "اخبار"],
["To Rescue", "Nejaat Daadan", "نجات دادن"],
["Wrench / Spanner", "Aachaar", "آچار"],
["To Enter / Arrive", "Vaared Shodan", "وارد شدن"],
["Treasure", "Ganj", "گنج"],
["(A) Cross", "Alaamat", "علامت"],
["(A) Shovel", "Beel", "بیل"],
["Car", "Khodro", "خودرو"],
["All Over (A Place)", "Saraasar", "سراسر"],
["Powerful", "Por Ghodrat", "پُر قدرت"],
["Luxurious", "Looks", "لوکس"],
["Population", "Jam'eeat", "جمعیّت"],
["Unnecessary", "Gheyr-e Zarooree", "غیرِ ضروری"],
["Necessary", "Zarooree", "ضروری"],
["Steel", "Foolaad", "فولاد"],
["Labourer / Blue Collar Worker", "Kaargar", "کارگر"],
["(A) Generation", "Nasl", "نسل"],
["Relatively", "Nesbatan", "نسبتاً"],
["The Same", "Yeksaan", "یکسان"],
["Quality", "Kayfeeat", "کیفیّت"],
["Production (Manufacturing)", "Toleed", "تولید"],
["Vehicle", "Vaseeleh-ye Naghlee-eh", "وسیلۀ نقلیّه"],
["Luck", "Bakht", "بخت"],
["Lottery", "Bakht Azmaaee", "بخت آزمایی"],
["Draw / Raffle", "Ghooreh Keshee", "قرعه کشی"],
["Optimistic", "Khoshbeen", "خوش بین"],
["Pessimistic", "Badbeen", "بدبین"],
["Minimum", "Hade'aghal", "حدّاقل"],
["Maximum", "Hade'aksar", "حدّاکثر"],
["Driving License", "Govaaheenaameh-ye Raanandegee", "گواهینامۀ رانندگی"],
["To Drive", "Raanandegee Kardan", "رانندگی کردن"],
["Dentist", "Dandaan Pezeshkee", "دندان پزشکی"],
["My Studies", "Tahseelam", "تحصیلم"],
["Relatives", "Aghvaam", "اقوام"],
['A Yawn', 'Khameeaazeh', 'خمیازه'],
["Elderly", ["Saalmand", "Mosen"], ["سالمند", "مسن"]],
["To Take Care Of", "Negahdaaree Kardan", "نگهداری کردن"],
['Individuals', 'Afraad', 'افراد'],
["Loser", "Baazandeh", "بازنده"],
["Subject (Studying)", "Reshteh", "رشته"],
["Rates (Of)", "Meezaan(e)", "میزان"],
["Cosmetic Surgery", "Jarraahee-ye Zeebaaee", "جرّاحیِ زیبایی"],
["Statistics", "Aamaar", "آمار"],
["Depressed", "Afsordeh", "افسرده"],
["To Remove", "Bar Taraf Kardan", "برطرف کردن"],
["In What Respect", "Az Cheh Nazar?", "از چه نظر؟"],
["Plastic Surgery", "Jarraahee-ye Pelaasteek", "جرّاحیِ پلاستیک"],
["No Doubt (I'm Sure)", "Shakee Neest", "شکی نیست"],
["Jacket", "Kaapshen", "کاپشن"],
["To Advance / Progress", "Peeshraft Kardan", "پیشرفت کردن"],
["Already", "Ghablan", "قبلا"],
["Expulsion / Dismissal", "Ekhraaj", "اخراج"],
["Beak", "Menghaar", "منقار"],
["To Peck", "Nok Zadan", "نوک زدن"],
["Odds And Ends", "Khert O Pert", "خرت و پرت"],
["Boot (Shoe)", "Pooteen", ["پوتین", "چکمه"]],
["Esfahan Is Half Of The World", "", "اصفهان را نصف جهان"],
["Anyway", "Beh Har Haal", "به هر حال"],
["Nice One (Street / Matey)", "Damet Garm", "دمت گرم"],
["Enthusiasm", "Zogh O Shogh", "ذوق و شوق"],
["Rocket", "Mooshak", "موشک"],
["(Outer) Space", "Fazaa", "فضا"],
["Spaceship", ["Fazaapeymaa", "Safeeneh"], ["فضاپیما", "سفینه"]],
["Freedom", "Aazaadee", "آزادی"],
["Probably", "Ehtemaalan", "احتمالاً"],
["Mental", "Roohee", "روحی"],
["Physical", "Jesmee", "جسمی"],
["Radiation", "Parto", "پرتو"],
["Asia", "Aaseeaa", "آسیا"],
["Continent", "Ghaareh", "قاره"],
["Middle-East", "Khaavare Meeaaneh", "خاورمیانه "],
["Land / Country", "Sarzameen", "سرزمین"],
["Caspian (Sea)", "Khazar", "خزر"],
["Peak (Mountain)", "Ghol-leh", "قلّه"],
["Desert / Wilderness", "Beeaabaan", "بیابان"],
['Building', ['Saakhtemaan', 'Banaa'], ['ساختمان', 'بنا']],
["Wealth", "Servat", "ثروت"],
["Export", "Saader", "صادر"],
['Bed', ['Takht', 'Rakhtekhaab', 'Bastar'], ['تخت', 'رختخواب', 'بستر']],
["Crown", "Taaj", "تاج"],
["Rope", "Tanaab", "طناب"],
["Long / Tall", "Deraaz", "دراز"],
["Brick", "Aajor", "آجر"],
["Crossroad / Intersection", "", "چهارراه"],
["Bubble", "Hobaab", "حباب"],
["Jackal / Hyena", "Shoghaal", "شغال"],
["Petal", "Golbarg", "گلبرگ"],
["Bullet", "Golooleh", "گلوله"],
["Coal", "Zoghaal", "زغال"],
["Reed / Straw", "Nay", "نی"],
["Fiction / Myth", "Afsaaneh", "افسانه"],
["To Drown / Sink", "Ghargh Shodan", "غرق شدن"],
["Turquoise", "Feeroozeh", "فیروزه"],
["Fog", "Meh", "مه"],
['Old (Thing)', ['Ghadeemee', 'Kohneh'], ['قدیمی', 'کهنه']],
["To Enter", "Vaared Shodan", "وارد شدن"],
["Greece", "Yoonaan", "یونان"],
["Refugee", "Panaahandeh", "پناهنده"],
["Downhill", "Sarpaaeeeenee", "سرپایینی"],
["Uphill", "Sarbaalaaee", "سربالایی"],
["Policeman", "Paasbaan", "پاسبان"],
["Curly", "Ferferee", "فرفری"],
["To Slip", "", "لیز خوردن"],
["Disgusting Smell (Stench)", "Boo-ye Gand", "بوی گند"],
["Magazine", "Majaleh", "مجله"],
["Razor", "Teegh", "تیغ"],
["Vest", "Zeerpoosh", "زیرپوش"],
["Armpit", "Zeer-e Baghal", "زیر بغل"],
["One Of A Pair", "Lengeh", "لنگه"],
["Mismatched", "Lengeh Beh Lengeh", "لنگه به لنگه"],
["To Kick", "Lagad Zadan", "لگد زدن"],
["To Swear (Promise)", "Ghasam Khordan", "قسم خوردن"],
["To Advise", "Naseehat Kardan", "نصیحت کردن"],
["Matchstick", "Choob-e Kebreet", "چوب کبریت"],
["To Shove / Thrust In", "Foroo Kardan", "فرو کردن"],
["Cushion", "Motakaa", "متکا "],
["To Pick Up / Take", "Bardaashtan", "برداشتن"],
["To Pluck", "Kandan", "کندن"],
["To Dig", "Zameen Kandan", "زمین کندن"],
["(A) Grave", "Ghabr", "قبر"],
["To Take Off Clothes", "Lebaas Dar Aavordan", "لباس در آوردن"],
["(A) Tap / Faucet", "Sheer-e Aab", "شیر آب"],
["Loofah", "Leef", "لیف"],
["To Hold (Something)", "Negah Daashtan", "نگه داشتن"],
["Tightly / Firmly", "Mohkam", "محکم"],
["Foam", "Kaf", "کف"],
];

// ['Fate',           'Ghesmat',        'قسمت'],
// ["", "", ""],
