CARDS = [
['Fart',           'Gooz',           'گوز'],
['Cow',            'Gaav',           'گاو'],
['Dog',            'Sag',            'سگ'],
['Cat',            'Gorbeh',         'گربه'],
['Chair',          'Sandali',        'صندلی'],
['Table',          'Meez',           'میز'],
['Wood',           'Choob',          'چوب'],
['Bin',            'Zobaale Daanee', 'زباله دانی'],
['Plate',          'Bashghab',       'بشقاب'],
['Spoon',          'Ghashogh',       'قاشق'],
['Fork',           'Changol',        'چنگال'],
['Coat',           'Kot',            'کت'],
['Scarf (head)',   'Roosaree',       'روسری'],
['Scarf (neck)',   'Shaal',          'شال'],
['Curtains',       'Parde',          'پرده'],
['Watch',          "Sa'at",          'ساعت'],
['Cupboard',       'Komod',          'کمد'],
['Socks',          'Jooraab',        'جوراب'],
['Jeans',          'Shalvaare Jean', 'شلوار جین'],
['T-Shirt',        'T-Shirt',        'تی شرت'],
['Jewellery',      'Javaaher',       'جواهر'],
['Mouth',          'Dahan',          'دهان'],
['Hair',           'Moo',            'مو'],
['Eye',            'Cheshm',         'چشم'],
['Window',         'Panjareh',       'پنجره'],
['Door',           'Dar',            'در'],
['Thing',          'Cheez',          'چیز'],
['Question',       'Soaal',          'سوال'],
['Country',        'Keshvar',        'کشور'],
['School',         'Madreseh',       'مدرسه'],
['Year',           'Saal',           'سال'],
['(A) Company',    'Sherkat',        'شرکت'],
['Number',         'Shomareh',       'شماره'],
['Room',           'Otaagh',         'اتاق'],
['Reality',        'Vaaghayiat',     'واقعیت'],
['Shoe',           'Kafsh',          'کفش'],
['Grey',           'Khakestaree',    'خاکستری'],
['Neck',           'Gardan',         'گردن'],
['Chest',          'Seeneh',         'سینه'],
['Chin',           'Chaaneh',        'چانه'],
['Heart',          'Ghalb',          'قلب'],
['Least',          'Kamtarin',       'کمترین'],
['Sleep',          'Khaab',          'خواب'],
['Dream',          'Rooeeaa',        'رویا'],
['Good',           'Khoob',          'خوب'],
['New',            'Jadeed',         'جدید'],
['First',          'Aval',           'اول'],
['Last',           'Akhar',          'آخر'],
['Correct',        'Dorost',         'درست'],
['Big',            'Bozorg',         'بزرگ'],
['Tall',           'Ghadboland',     'قد بلند'],
['Short',          'Kootah',         'کوتاه'],
['Learn',          'Yaadgiree',     'یادگیری'],
[['Long', 'High', 'Loud'], 'Boland', 'بلند'],
['Low',            'Paeeeen',        'پایین'],
['Next',           'Ba-d',           'بعد'],
['Early',          'Zood',           'زود'],
['Young',          'Javaan',         'جوان'],
['Important',      'Mohem',          'مهم'],
['Public',         'Omoomee',        'عمومی'],
['Private',        'Khosoosee',      'خصوصی'],
['Under',          'Zeer',           'زیر'],
['Above',          'Baala',          'بالا'],
['Heavy',          'Sangeen',        'سنگین'],
['Light (Weight)', 'Sabok',          'سبک'],
['Weak',           "Za'eef",         'ضعیف'],
['Strong',         'Ghavee',         'قوی'],
['Rude',           'Beeaadab',       'بی ادب'],
['Polite',         "Moa'dab",        'مودب'],
['Most',           'Bishtarin',      'بیشترین'],
['To Follow',      'Donbaal Kardan', 'دنبال کردن'],
['Tree',           'Derakht',        'درخت'],
['Sea',            'Dareeah',        'دریا'],
['Ceiling',        'Saghf',          'سقف'],
['Bottom',         ['Kaf', 'Tah'],   ['کف','ته']],
['Stairs',         'Peleh',          'پله'],
['Train',          'Ghataar',        'قطار'],
['Danger',         'Khatar',         'خطر'],
['Horse',          'Asb',            'اسب'],
['Mouse',          'Moosh',          'موش'],
['Fish',           'Maahi',          'ماهی'],
['Puppy',          'Toole Sag',      'توله سگ'],
['Sheep',          'Goosfand',       'گوسفند'],
['Lamb (Animal)',  'Bareh',          'بره'],
['Lamb (Food)',    'Gooshte Bar-e',  'گوشت بره'],
['Chicken',        'Jooje',          'جوجه'],
['Hen',            'Morgh',          'مرغ'],
['Pig',            'Khook',          'خوک'],
['Pork',           'Goosht-e Khook', 'گوشت خوک'],
['Rabbit',         'Khargoosh',      'خرگوش'],
['Forehead',       'Peeshaanee',     'پیشانی'],
['Dictionary',     'Ketaab Tarjomeh', 'کتاب ترجمه'],
['Apple',          'Seeb',           'سیب'],
['Egg',            'Tochm-e Morgh',  'تخم مرغ'],
['Banana',         'Moz',            'موز'],
['Pineapple',      'Anaanaas',       'اناناس'],
['Nectarine',      'Shaleel',        'شلیل'],
['Olive',          'Zeytoon',        'زیتون'],
['Pistachio',      'Pesteh',         'پسته'],
['Rice (Cooked)',  'Polo',           'پلو'],
['Rice (Uncooked)','Berenj',         'برنج'],
['Hat',            'Kaala',          'کلاه'],
['Ham',            'Zhambon',        'ژامبون'],
['Vegetable',      'Sabzee',         'سبزی'],
['Fruit',          'Meeve',          'میوه'],
['Aftenoon',       'Asr',            'عصر'],
['Walking',        'Rah Raftan',     'راه رفتن'],
['Laughter',       'Khande',         'خنده'],
['Cry',            'Geryeh',         'گریه'],
['Cheek',          'Gooneh',         'گونه'],
['Kind',           'Mehrabaan',      'مهربان'],
['Cruel',          'Beerahm',        'بی رحم'],
['Funny',          'Khande Daar',    'خنده دار'],
[['Hand', 'Arm'],  'Dast',           'دست'],
['Tooth',          'Dandaan',        'دندان'],
[['Tongue', 'Language'],         'Zabaan',         'زبان'],
['Stupid',         'A-hmagh',        'احمق'],
['Open',           'Baaz',           'باز'],
['Teacher',        'Mohalem',        'معلم'],
['Mountain',       'Kooh',           'کوه'],
['Monster',        'Heyoolah',       'هیولا'],
['Brain',          'Maghz',          'مغز'],
['Glasses',        'Aynak',         'عینک'],
['Rain',           'Baaraan',        'باران'],
['Cloud',          'Abr',            'ابر'],
['Spring (Season)','Bahaar',         'بهار'],
['Summer',         'Taabestaan',     'تابستان'],
['Autumn',         'Paaeeeez',       'پاییز'],
['Winter',         'Zamestaan',      'زمستان'],
['Wedding',        'Aroosee',        'عروسی'],
['Poet',           'Shaaer',         'شاعر'],
['Poem',           'Shehr',          'شعر'],
['Healthy',        'Saalem',         'سالم'],
['Sad',            'Ghamgeen',       'غمگین'],
['Tight',          'Tang',           'تنگ'],
['Loose',          'Shol',           'شل'],
['Pull',           'Kesheedan',      'کشیدن'],
['Push',           'Hol Daadan',     'هل دادن'],
['Hill',           'Tapeh',          'تپه'],
['Wind',           'Baad',           'باد'],
['Bag',            'Keef',           'کیف'],
['Candle',         'Shamh'           'شمع'],
['Fire',           'Aatish',         'آتش'],
['Swimming',       'Shenaa',         'شنا'],
['Hot',            'Daagh',          'داغ'],
['Thin (Weight)',  'Laaghar',        'لاغر'],
['Elevator',       'Aasaansaar',     'آسانسور'],
['Mirror',         'Ayneh',          'اینه'],
['Smile',          'Labkhand',       'لبخند'],
['Bird',           'Parandeh',       'پرنده'],
['Downstairs',     'Tabaghe Paaeen', 'طبقه پایین'],
['Eating',         'Khordan',        'خوردن'],
['Drinking',       'Noosheedan',     'نوشیدن'],
['Empty',          'Khaalee',        'خالی'],
['Full',           'Por',            'پر'],
['Rich',           'Servatmand',     'ثروتمند'],
['Poor',           'Fagheer',        'فقیر'],
['Donkey',         'Khar',           'خر'],
['Ugly',           'Zesht',          'زشت'],
['Grass',          'Chaman',         'چمن'],
['Line',           'Khat',           'خط'],
['To Arrive',      'Reseedan',       'رسیدن'],
['Step',           ['Ghadam', 'Gaam'],         ['قدم', 'گام']],
['A Screw',        'Peech',          'پیچ'],
['Hopeless',       'Naa-omeed',      'ناامید'],
['Patience',       'Sabr',           'صبر'],
['Until',          'Taa',            'تا'],
['Snow',           'Barf',           'برف'],
['Sudden',         'Naagahaanee',    'ناگهانی'],
['Start',          'Shoroo',         'شروع'],
['Overflowing',    'Labreez',        'لبریز'],
['Dust',           'Ghobaar',        'غبار'],
['Energy',         'Enerzhee',       'انرژی'],
['Silence',        'Sokoot',         'سکوت'],
['Daily',          'Roozaaneh',      'روزانه'],
['Take',           'Gereft',         'گرفت'],
['Pedestrian',     'Rahgozar',       'رهگذر'],
['Shadow',         'Saayeh',         'سایه'],
['Moon',           'Maah',           'ماه'],
['Voice',          'Sedaa',          'صدا'],
['Old (Person)',   'Pee-r',          'پیر'],
['12',             'Davaazdeh',      'دوازده'],
[['Light (Colour)', 'Bright'],         'Roshan',         'روشن'],
['Grandchild',     'Naveh',          'نوه'],
['Around',         'D-oor',          'دور'],
['[Him/Her]self',  'Khodesh',        'خودش'],
['Total',          'Jamh',           'جمع'],
['Stream',         'Jooeebaar',      'جویبار'],
['Stone',          'S-ang',          'سنگ'],
['Wall',           'Deivaar',        'دیوار'],
['Back (Behind)',  ['Posht', 'Aghab'], ['پشت', 'عقب']],
['Moss',           'Khazeh',         'خزه'],
['Wallet / Purse', 'Keef-e Pool',    'کیف پول'],
['Handbag',        'Keef-e Dastee',  'کیف دستی'],
['Fist',           'Mosht',          'مشت'],
['Soldier',        'Sarbaaz',        'سرباز'],
['Crazy',          'Deevaaneh',      'دیوانه'],
['Foreigner',      'Khaarejee',      'خارجی'],
['Word',           'Kalameh',        'کلمه'],
['Brave',          'Shojaa',         'شجاع'],
['Happened',       'Shodeh',         'شده'],
['Moonlight',      'Mahtaab',        'مهتاب'],
['Their',          'Shaan',          'شان'],
['Fell',           'Aaftaad',        'افتاد'],
['Story',          ['Daastaan', 'Gheseh'],       ['داستان', 'قصه']],
['Mixed',          'Ghaatee',        'قاتی'],
['Other',          'Digar',          'دیگر'],
['Put',            'Gozaasht',       'گذاشت'],
['Reluctance',     'Bee Maylee',     'بی میلی'],
['Side',           'Taraf',          'طرف'],
['Returned',       'Barmeegasht',    'برمیگشت'],
['Time',           ['Vaght', 'Daf\'eh'],          ['وقت', 'دفعه']],
['Imagination',    'Kheeaal',        'خیال'],
['Testicle',       'Bayzeh',         'بیضه'],
['Busy',           'Mashghool',      'مشغول'],
['To Make',        'Dorost Kardan',  'درست کردن'],
['Thick',          'Koloft',         'کلفت'],
['Branch',         'Shakhe',         'شاخه'],
['Ear',            'Goosh',          'گوش'],
['Repeat',         'Tekraar',        'تکرار'],
['Pimp',           'Jaakesh',        'جاکش'],
['Level',          'Tabagheh',       'طبقه'],
['Box',            'Ja\'beh',        'جعبه'],
['To (Give) Promise', 'Ghol Daadan', 'قول دادن'],
['Circumcision',   'Khatneh',        'ختنه'],
['Accident',       'Tasaadof',       'تصادف'],
['To Wake Up',     'Beedaar Kardan', 'بیدار  کردن'],
['Polluted',       'Aaloodeh',       'آلوده'],
['Sleepy',         'Khaabaaloodeh',  'خواب آلوده'],
['Skin',           'Poost',          'پوست'],
['Forest',         'Jangal',         'جنگل'],
['Interesting',    'Jaaleb',         'جالب'],
['Potato',         'Seeb Zameenee',  'سیب زمینی'],
['Earth',          'Zameen',         'زمین'],
['Onion',          'Peeaaz',         'پیاز'],
['Pomegranate',    'Anaar',          'انار'],
[['Spicy', 'Fast'], 'Tond',          'تند'],
['Reading',        'Khaandan',       'خواندن'],
['Circle',         'Daayereh',       'دایره'],
['Square',         'Morabah',        'مربع'],
['Kick',           'Paa Zadan',      'پا زدن'],
['To Travel',      'Safar Kardan',   'سفر کردن'],
['Tower',          'Borj',           'برج'],
['Perfume',        'Atr',            'عطر'],
['Suitcase',       'Chamadaan',      'چمدان'],
['Drunk',          'M-ast',          'مست'],
['Yet / Still',    'Hanooz',         'هنوز'],
['Dark (Colour)',  'Teereh',         'تیره'],
['Rhino',          'Kargadan',       'کرگدن'],
['Stop!',          'Eest',           'ایست'],
['Sew your lips',  'Lab dooz',       'لب دوز'],
['Comfortable',    'Raahat',         'راحت'],
['Wheel',          'Charkh',         'چرخ'],
['Bike',           'Docharkhe',      'دوچرخه'],
['To Smoke',       'Dood Kardan',    'دود کردن'],
['Spider',         'Ankaboot',       'عنکبوت'],
['Saliva',         'Bozagh',         'بزاق'],
['Pillow',         'Baalesh',        'بالش'],
['Duvet',          'Lahaaf',         'لحاف'],
['Sky',            'Aasemaan',       'آسمان'],
['Against',        'Aley-he',        'علیه'],
['Prison',         'Zendaan',        'زندان'],
['Salt',           'Namak',          'نمک'],
['Sweet',          'Sheereen',       'شیرین'],
['Sour',           'Torsh',          'ترش'],
['Dagger',         'Khanjar',        'خنجر'],
['Together',       'Baa ham',        'با هم'],
['Go!',            'Boro',           'برو'],
['Child / Offspring', 'Farzand',     'فرزند'],
[['By the way', 'Actually'],     'Raastee',        'راستی'],
['Complaint',      'Shekaaeeat',     'شکایت'],
['Roam Around',    'Gardesh Kardan', 'گردش کردن'],
['Possible',       'Momken',         'ممکن'],
['To Get Up',      'Paasho',         'پاشو'],
['Decision',       'Tasmeem',        'تصمیم'],
['To Decide',      'Tasmeem Gereftan', 'تصمیم گرفتن'],
['To Go',          'Beravam',        'بروم'],
['To Find',        'Paydaa Kardan',  'پیدا کردن'],
['News',           'Khabar',         'خبر'],
['(At the) Time',  'Mogh-e',         'موقع'],
['Someone',        'Kasee',          'کسی'],
['Memory',         'Yaad',           'یاد'],
['I Remembered',   'Yaadam Omad',    'یادم امد'],
['Meaning',        ['Y\'anee', 'M\'anee'],        ['یعنی', 'معنی']],
['Piece',          'Tekeh',          'تکه'],
['Finished',       'Tamaam Shod',    'تمام شد'],
['North',          'Shomaal',        'شمال'],
['South',                       'Jonoob',                    'جنوب'],
['East',                        'Shargh',                    'شرق'],
['West',                        'Gharb',                     'غرب'],
['Butter',                      'Kareh',                     'کره'],
['Pair',                        'Joft',                      'جفت'],
['Bench',                       'Neemkat',                   'نیمکت'],
['Park',                        'Paark',                     'پارک'],
['Underwear',                   'Lebaas-e Zeer',             'لباس زیر'],
['Library',                     'Ketaabkhaane',              'کتابخانه'],
['Umbrella',                    'Chatr',                     'چتر'],
['Hundred',                     'Sa-d',                      'صد'],
['Jealous',                     'Hasood',                    'حسود'],
['Regret',                      'Hasrat',                    'حسرت'],
['One Time',                    'Yek Daf\'eh',               'یک دفعه'],
['Seed',                        'Daaneh',                    'دانه'],
['Edge',                        'Kenaareh',                  'کناره'],
['Taxi Driver',                 'Raanandeh Taaksi',          'راننده تاکسی'],
['Between',                     'Meeaan',                    'میان'],
['However',                     'Albateh',                   'البته'],
['Broken',                      'Shekasteh',                 'شکسته'],
['Outside',                     'Beeroon',                   'بیرون'],
['To Understand',               'Fahmeedan',                 'فهمیدن'],
['Groan',                       'Naaleh',                    'ناله'],
['To curse someone',            'Nefreen',                   'نفرین'],
['(If you were) To Go',         'Beravee',                   'بروی '],
['Until you get old',           'Taa Peer Shavee',           'تا پیر شوی'],
['A Certain Way',               'Tor',                       'طور'],
['Net',                         'Toor',                      'تور'],
['Has your head been hit?',     'Magar be saret zadeh?',     'مگر بسرت زده؟'],
['Neighbour',                   'Hamsaayeh',                 'همسایه'],
['Tell Don\'t Tell (Chitchat)', 'Begoo Magoo',               'بگو مگو'],
['As Though',                   'Engaar',                    'انگار'],
['In the era (of)',             'Zamaaneh',                  'زمانه'],
['Blind',                       'Koor',                      'کور'],
['They Give',                   'Bedahand',                  'بدهند'],
['Sometimes',                   'Gaahee',                    'گاهی'],
['(I) Get Going',               'Rah Beoftam',               'راه بیفتم'],
['Turned Out Well',             'Khoob Daraamadeh',          'خوب درآمده'],
['In a nonsensical fashion',    'Beekhodee',                 'بیخودی'],
['Small unit of measurement',   'Vaajab',                    'واجب'],
['Wise',                        'Aalem',                     'عالم'],
['Philosopher',                 'Feelsoof',                  'فیلسوف'],
['Only',                        'Faghat',                    'فقط'],
['Fake',                        'Alakee',                    'الکی'],
['Wicked',                      'Badjens',                   'بدجنس'],
['In this way',                 'Eentoori',                  'اینطوری'],
['Tomato',                      'Gojeh Farangi',             'گوجه فرنگی'],
['Childhood',                   ['Koodaki', 'Bacchegi'],     ['کودکی', 'بچگی']],
['Noisy Chaos',                 ['Hayaahoo', 'Harj o Marj'], ['هیاهو', 'هرج  و مرج']],
['Coin',                        'Sek-keh',                   'سکه'],
['Banknote',                    'Eskenaas',                  'اسکناس'],
['Scissors',                    'Ghaychee',                  'قیچی'],
['Wolf',                        'Gorg',                      'گرگ'],
['Lizard',                      'Maarmoolak',                'مارمولک'],
['Bye (For Now)',               'Fehlan',                    'فعلا'],
['Hope to see you again',       'Be Omide Didar',            'به امیده دیدار'],
['Until Later',                 'Taa Ba-d',                  'تا بعد'],
['Until Tomorrow',              'Taa Fardaa',                'تا فردا'],
['Where are you from?',         'Taa Ahle Koja Hasti?',      'تو اهله کجا هستی؟'],
['I Live In London',            'Man Dar Landan Zendegi Mikonam', 'من در لندن زندگی می کنم'],
['Lawyer',                      'Vakeel',                    'وکیل'],
['Author',                      'Neveesandeh',               'نویسنده'],
['Factory',                     'Karkhaaneh',                'کارخانه'],
['What\'s your job?',           'Che Kaar-e Hasti?',          'چه کار هستی'],
['Husband',                     'Shohar',                    'شوهر'],
['Tray',                        'Seenee',                    'سینی'],
['Bee',                         'Zanboor',                   'زنبور'],
['Gift',                        ['Hedyeh', 'Kaado'],         ['هدیه', 'کادو']],
['Vinegar',                     'Serkeh',                    'سرکه'],
['Nonsense',                    'Mozakhraf',                 'مزخرف'],
[['Comb', 'Shoulder'],          'Shaaneh',                   'شانه'],
['Toothbrush',                  'Mesvaak',                   'مسواک'],
['Soap',                        'Saaboon',                   'صابون'],
['Mosque',                      'Masjed',                    'مسجد'],
['Flag',                        'Parcham',                   'پرچم'],
['Suitable',                    'Monaaseb',                  'مناسب'],
['Bakery',                      'Naanvaaee',                 'نانوایی'],
['Retired',                     'Baazneshasteh',             'بازنشسته'],
['Newsagent',                   'Rooznaameh Forooshee',      'روزنامه فروشی'],
['To Sell',                     'Forookhtan',                'فروختن'],
['Page',                        'Safeh',                     'صفحه'],
['To Throw',                    'Andaakhtan',                'انداختن'],
[['Playground', 'Yard', 'Courtyard'], 'Hayaat',              'حیاط'],
['To Clean',                    'Tameez Kardan',             'تمیز کردن'],
['Board',                       'Takhteh',                   'تخته'],
['Blackboard',                  'Takhteh Siaa',              'تخته سیاه'],
['Nature',                      'Tabeeat',                   'طبیعت'],
['Chocolate',                   'Shokolaat',                 'شکلات'],
['Music',                       'Mooseghee',                 'موسیقی'],
['Exercise',                    'Varzesh',                   'ورزش'],
['Fiancé',                      'Naamzad',                   'نامزد'],
['Cheap',                       'Aarzaan',                   'ارزان'],
['Ant',                         'Moorcheh',                  'مورچه'],
['Frying Pan',                  'Maahee Taabeh',             'iماهی تابه'],
['Ladle',                       'Malaagheh',                 'ملاقه'],
['Cabbage',                     'Kalam',                     'کلم'],
['Wow!',                        'Bah bah!',                  'به به'],
['Almond',                      'Baadaam',                   'بادام'],
['Real',                        'Vaagh-e-ee',                'واقعی'],
['Picture',                     'Tasveer',                   'تصویر'],
['Animal',                      'Heyvaan',                   'حیوان'],
['Without',                     'Beeaanke',                  'بی آنکه'],
['Insect',                      'Saas',                      'ساس'],
['Sam',                         'Poison',                    'سم'],
['Bride',                       'Aroos',                     'عروس'],
['Rooster',                     'Khoroos',                   'خروس'],
[['(A) Groom', 'Son In Law'],   'Daamaad',                   'داماد'],
['Price',                       'Gheymat',                   'قیمت'],
['Marble (Ball)',               'Teeleh',                    'تیله'],
['(A) Swing',                   'Taab',                      'تاب'],
['(A) Whistle',                 'Soot',                      'سوت'],
['Sweat',                       'Aragh',                     'عرق'],
['Iraq',                        'Araagh',                    'عراق'],
['Strength',                    'Zoor',                      'زور'],
['Template of Strength',        'Zoorkhaane',                'زورخانه'],
['Upper Arm',                   'Baazoo',                    'بازو'],
['Needle',                      'Soozan',                    'سوزن'],
['She Sews',                    'Midoozad',                  'می دوزد'],
['Knee',                        'Zaanoo',                    'زانو'],
['Goose',                       'Ghaaz',                     'غاز'],
['Tool',                        'Abzaar',                    'ابزار'],
['Basement',                    'Ziirzameen',                'زیر زمین'],
['Underground',                 'Ziir Zameen',               'زیر  زمین'],
['(He) Makes',                  'Misaazad',                  'می سازد'],
['To Make',                     'Saakhtan',                  'ساختن'],
['Toy',                         'Asbaab Baazi',              'اسباب بازی'],
['Giraffe',                     'Zarraafe',                  'زرافه'],
['How\'s It Going',             'Chetour Peesh Mireh',       'چطور پیش میره'],
['I\'m learning Farsi',         'Daaram Farsi Yaad Migiram', 'دارم فارسی یاد می گیرم'],
['Kitchen',                     'Aashpazkhaaneh',            'اشپزخانه'],
['Art',                         'Honar',                     'هنر'],
['Turtle',                      'Laakposht',                 'لاک پشت'],
['To Fly',                      'Parvaaz Kardan',            'پرواز کردن'],
['To Speak',                    'Sohbat',                    'صحبت'],
['Please speak more slowly',    'Lotfan Yavaashtar Sohbat Konid', 'لطفآ یواش تر صحبت کنید'],
['What is it in Farsi?',        'Beh Farsi Chi Mishe?',      'به فارسی چی میشه'],
['Camera',                      'Doorbeen',                  'دوربین'],
['This Alone',                  'Tanhaa Hameen',             'تنها همین'],
['I am killing',                'Mikosham',                  'می کشم'],
['To Kill',                     'Koshtan',                   'کشتن'],
['(A) Type',                    'Joor',                      'جور'],
['To Digest',                   'Hazm Kardan',               'هضم کردن'],
['(A) Design',                  'Tarraahee',                 'طراحی'],
['(A) Translation',             'Tarjomeh',                  'ترجمه'],
['Bank Account',                'Hesaabe Baanki',            'حساب بانکی'],
['Order (Given)',               'Dastoor',                   'دستور'],
['Secret',                      'Raaz',                      'راز'],
['Are You Ready?',              'Haazeri',                   'حاضری'],
['Snake',                       'Maar',                      'مار'],
['But',                         ['Vali', 'Balkeh'],          ['ولی', 'بلکه']],
['I Can',                       'Meetavaanam',               'می توانم'],
['Single',                      'Tek',                       'تک'],
['(Current) Status',            'Ahvaal',                    'احوال'],
['Wing',                        'Baal',                      'بال'],
['Africa',                      'Aafrighaa',                 'آفریقا'],
['Nut (Bolt)',                  'Mohreh',                    'مهره'],
['Flame',                       'Shoh-leh',                   'شعله'],
['Earthquake',                  'Zelzeleh',                  'زلزله'],
['Discount',                    'Takhfeef',                  'تخفیف'],
['Sword',                       'Shamsheer',                 'شمشیر'],
['Gun',                         'Tofang',                    'تفنگ'],
['Gather Round',                'Jamh Sheed',                'جمع شید'],
['Pain',                        'Dard',                      'درد'],
['That Hit The Spot',           'Chasbeed',                  'چسبید'],
['Backpack',                    'Kooleh Poshtee',            'کوله پشتی'],
['Beach',                       'Saahel',                    'ساحل'],
['Seaside',                     'Lab-e Dareaa',              'لب دریا'],
['Government',                  ['Hokoomat', 'Daolat'],      ['حکومت', 'دولت']],
['Stingy',                      'Khasees',                   'خسیس'],
['Demon',                       'Deev',                      'دیو'],
['Metal',                       'Felez',                     'فلز'],
['Creature',                    'Jaanevar',                  'جانور'],
['Rock',                        'Sakhreh',                   'صخره'],
['Welcome',                     'Khosh Aamadeed',            'خوش آمدید'],
['(The) Moment',                'Lahzeh',                    'لحظه'],
['Breath',                      'Nafas',                     'نفس'],
['Dove',                        'Kabootar',                  'کبوتر'],
['Life (span)',                 'Omr',                       'عمر'],
['Dancing',                     'Raghs',                     'رقص'],
['Sparkle',                     'Talaalo',                   'تلالو'],
['Don\'t Worry',                'Na-tars',                   'نترس'],
['Suffering',                   'Ranj',                      'رنج'],
['Food',                        ['Ghazaa', 'Khooraakee'],    ['غذا', 'خوراکی']],
['Prostitution',                'Fahshaa',                   'فحشا'],
['Pipe',                        'Looleh',                    'لوله'],
['Pocket',                      'Jeeb',                      'جیب'],
['To Wink',                     'Cheshmak Zadan',            'چشمک زدن'],
['Alley',                       'Koocheh',                   'کوچه'],
['Swearword',                   'Fohsh',                     'فحش'],
['Leaf',                        'Barg',                      'برگ'],
['Soul',                        'Rooh',                      'روح'],
['Sun',                         ['Aaftaab', 'Khoorsheed'],   ['افتاب', 'خورشید']],
['Breeze',                      'Naseem',                    'نسیم'],
['Rubbish (Trash)',             'Aashghaal',                 'آشغال'],
['Joke',                        'Shookhee',                  'شوخی'],
['(A) Savage',                  'Vahshee',                   'وحشی'],
['Half',                        ['Neem', 'Nesf'],            ['نیم', 'نصف']],
['(A) Drop',                    'Ghatreh',                   'قطره'],
['Orphan',                      'Yateemee',                  'یتیمی'],
['(Dog) Bark',                  'Paars',                     'پارس'],
['Fatty',                       'Charb',                     'چرب'],
['Sending Someone To Coventry', 'Ghahr',                     'قهر'],
['Fig',                         'Anjeer',                    'انجیر'],
['Destruction',                 'Veeraanee',                 'ويرانی'],
['Light (Sun)',                 'Noor',                      'نور'],
['Death',                       'Marg',                      'مرگ'],
['Listen!',                     'Beshno',                    'بشنو'],
['Again',                       'Dobare',                    'دوباره'],
['Wave (Sea)',                  'Moj',                       'موج'],
['Naughtiness',                 'Sheytooni',                 'شیطونی'],
['Eyelid',                      'Pelk',                      'پلک'],
['A Fly', 	                    'Magasee',                   'مگسی'],
['You Have The Right', 	        'Hagh Daaree',               'حق داری'],
['Wage', 	                      'Mozd',                      'مزد'],
['Trouble', 	                  'Dardesar',                  'دردسر'],
['To Help', 	                  'Komak Kardan',              'کمک کردن'],
['Goat', 	                      'Boz',                       'بز'],
['Grape',                       'Aangoor',                   'انگور'],
['Peach',                       'Holoo',                     'هلو'],
['Yellow',                      'Zard',                      'زرد'],
['Fence',                       'Nardeh',                    'نرده'],
['Ladder',                      'Nardebaan',                 'نردبان'],
['Ice',                         'Yakh',                      'یخ'],
['Heaven',                      'Behesht',                   'بهشت'],
['Shepherd',                    'Choopaan', 'چوپان'],
['Mushroom',                    'Ghaarch', 'قارچ'],
['Fountain',                    'Cheshmeh', 'چشمه'],
['Network', 'Shabkeh', 'شبکه'],
['Angry',                       'Asabaanee', 'عصبانی'],
['Even',                        'Hat\'taa', 'حتی'],
['Soon',                        'Behzoodee', 'به زودی'],
['The Tip',                     'Nok', 'نک'],
['To Bend',                     'Kham Shodan', 'خم شدن'],
['To Wear',                     'Poosheedan', 'پوشیدن'],
['Electricity',                 'Bargh', 'برق'],
['Scary', 'Tarsnaak', 'ترسناک'],
['Thunder', 'Rad', 'رعد'],
['Terrified', 'Zahreh Tark', 'زهره ترک'],
['To Burst', 'Tarkeed', 'ترکید'],
['Horrible', 'Vahshatnaak', 'وحشتناک'],
['Layer', 'Laayeh', 'لایه'],
['To Exit', 'Khaarej Shodan', 'خارج شدن'],
['Dark', 'Taareek', 'تاریک'],
['Bizarre', 'Ghareeb', 'غریب'],
['Carrot', 'Haveej', 'هویج'],
['Shirt', 'Peeraahan', 'پیراهن'],
['Overcoat', 'Paalto', 'پالتو'],
['Towel', 'Holeh', 'حوله'],
['Bridge', 'Pol', 'پل'],
['Pharmacy', 'Daarookhaane', 'داروخانه'],
[['Drug', 'Medicine'], 'Daaroo', 'دارو'],
['Shopping', 'Khareed', 'خرید'],
['Paper', 'Kaaghaz', 'کاغذ'],
['Bowl', 'Kaaseh', 'کاسه'],
['Credit Card', 'Kaart-e Etebaaree', 'کارت اعتباری'],
['Fast', 'Sareeh', 'سریع'],
['Director', 'Kaargardaan', 'کارگردان'],
['Festival', 'Jashnvaareh', 'جشنواره'],
['A Group', 'Gorooh', 'گروه'],
['Chewing Gum', 'Aadaams', 'آدامس'],
['Strawberry', 'Toot Farangi', 'توت فرنگی'],
['Mulberry', 'Toot', 'توت'],
['Date (Fruit)', 'Khormaa', 'خرما'],
['Plum', 'Aaloo', 'آلو'],
['Queen', 'Malakeh', 'ملکه'],
['What\'s On Your Mind?', 'Dar Che Fekr Hastid', 'در چه فکر هستید'],
['To Surprise', 'Mota\'a\'jeb Kardan', 'متعجب کردن'],
['Planet', 'Sayaareh', 'سیاره'],
['Swimming Pool', 'Estakhr', 'استخر'],
['Church', 'Keleesaa', 'کلیسا'],
['Synagogue', 'Keneeseh', 'کنیسه'],
['Walnut', 'Gerdoo', 'گردو'],
['Jam', 'Mora\'baa', 'مربا'],
['Pepper', 'Felfel', 'فلفل'],
['Dessert', 'Deser', 'دسر'],
['Mate', 'Rafeegh', 'رفیق'],
['Darling', 'Naazaneem', 'نازنینم'],
['Brains And Wit', 'Aghl o Hoosh', 'عقل و هوش'],
['I had a great time', 'Kheili khosh gozaasht', 'خیلی خوش گذاشت'],
['I need to get going', 'Baayad yavaash yavaash beram', 'باید یواش یواش برم'],
['String', 'Nakh', 'نخ'],
['Crab', 'Kharchang', 'خرچنگ'],
['Worm', 'Kerm', 'کرم'],
['Blossom', 'Shokoofeh', 'شکوفه'],
['Nightingale', 'Bolbol', 'بلبل'],
['Butterfly', 'Parvaaneh', 'پروانه'],
['Restlessness', 'Beegharaaree', 'بی قراری'],
['Crack', 'Shekaaf', 'شکاف'],
['Same Gender', 'Hamjens', 'همجنس'],
['Waterfall', 'Aabshaar', 'آبشار'],
['Hunter', 'Shekaarchee', 'شکارچی'],
['A Stranger', 'Ghareebeh', 'غریبه'],
['River', 'Roodkhaaneh', 'رودخانه'],
['Pilot', 'Khalabaan', 'خلبان'],
['Airport', 'Foroodgaah', 'فرودگاه'],
['Enough', 'Kaafee', 'کافی'],
['Hunting', 'Shekaar', 'شکار'],
['Sugar', 'Shekar', 'شکر'],
['Robin', 'Seenehsorkh', 'سینه سرخ'],
['Delicate', 'Lateef', 'لطیف'],
['Let Me Be', 'Raahatam Bezaar', 'راحتم بذار'],
['Pond', 'Berkeh', 'برکه'],
['The Center', 'Markaz', 'مرکز'],
['Unhappy', 'Naaraahat', 'ناراحت'],
['To Love', 'Aashegh', 'عاشق'],
['Closed', 'Tateel', 'تعطیل'],
['Opponent', 'Hareef', 'حریف'],
['Referee', 'Daavar', 'داور'],
['Satisfied', 'Raazee', 'راضی'],
['Victory', 'Peeroozee', 'پیروزی'],
['Winner', 'Barandeh', 'برنده'],
['Lucky', 'Khoshshaans', 'خوش شانس'],
['How Much', 'Cheghadr', 'چقدر'],
['To Practice', 'Tamreen Kardan', 'تمرین کردن'],
['Chemical', 'Sheemeeaaee', 'شیمیایی'],
['I Heard', 'Sheneedam', 'شنیدم'],
['Bomb', 'Bom-b', 'بمب'],
['Explosion', 'Aanfejaar', 'انفجار'],
['Crowded', 'Sholoogh', 'شلوغ'],
['Sneakily', 'Yavaashakee', 'یواشکی'],
['Mistake', 'Eshtebaah', 'اشتباه'],
['Vomit', 'Estefraagh', 'استفراغ'],
['(A) Second', 'Saanyeh', 'ثانیه'],
['Cool', 'Khonak', 'خنک'],
['Garden', 'Baagh', 'باغ'],
['Blonde', 'Boor', 'بور'],
['Red', ['Ghermez', 'Sorkh'], ['قرمز', 'سرخ']],
['Quick', 'Ferz', 'فرز'],
['Humid', 'Martoob', 'مرطوب'],
['It\'s Raining', 'Daare Baaraan Miaad', 'داره باران میاد'],
['It\'s Going To Rain', 'Baaraan Miaad', 'باران میاد'],
['Dry', 'Khoshk', 'خشک'],
['Friendship', 'Doostee', 'دوستی'],
['Give Me A Kiss', 'Boos Bedeh', 'بوس بده'],
['Elf', 'Vooroojak', 'وروجک'],
['Tiny', 'Fesghelee', 'فسقلی'],
['Map', 'Naghsheh', 'نقشه'],
['Scenery', 'Manzareh', 'منظره'],
['Steering Wheel', 'Farmaan', 'فرمان'],
['Cape', 'Shenel', 'شنل'],
['Junk', 'Bonjol', 'بنجل'],
['Cucumber', 'Kheeaar', 'خیار'],
['Neighbourhood', 'Mahaleh', 'محله'],
['How old are you?', 'Chand saal daarid?', 'چند سال دارید؟'],
['Weekend', 'Aakhar-e Hafteh', 'آخر هفته'],
['Around', 'Atraaf', 'اطراف'],
['Resident', 'Saaken', 'ساکن'],
['Until Now', 'Taa Be Haal', 'تا به حال'],
['Nourishment', 'Aazogheh', 'آذوقه'],
['Fall of (Rain/Snow)', 'Baaresh', 'بارش'],
['Parrot', 'Tootee', 'طوطی'],
['Arranged', 'Cheedeh', 'چیده'],
['Newborn', 'No-zaad', 'نوزاد'],
['Iranian Fiddle', 'Kamaancheh', 'کمانچه'],
['Law', 'Ghaanoon', 'قانون'],
['Cello', 'Veeolinsel', 'ویولنسل'],
['Violin', 'Veeolin', 'ویولن'],
['Clarinet', 'Klaareenet', 'کلارینت'],
['Lemon', 'Leemoo', 'لیمو'],
['Zero', 'Sefr', 'صفر'],
['2nd', 'Do-vom', 'دوم'],
['3rd', 'Se-vom', 'سوم'],
['4th', 'Chahaar-om', 'چهارم'],
['5th', 'Panj-om', 'پنجم'],
['6th', 'Shesh-om', 'ششم'],
['7th', 'Haft-om', 'هفتم'],
['8th', 'Hasht-om', 'هشتم'],
['9th', 'Noh-om', 'نهم'],
['10th', 'Dah-om', 'دهم'],
['Not Working', 'Kharaab', 'خراب'],
['Front', 'Jelo', 'جلو'],
['Next (To)', 'Kenaar', 'کنار'],
['Interior', 'Daakheleh', 'داخله'],
['Once Per Day', 'Har Rooz Yek Baar', 'هر روز یک بار'],
['Opposite (To)', 'Rooberoo', 'روبرو'],
['Bag (Sack)', 'Keeseh', 'کیسه'],
['Wheat', 'Gandom', 'گندم'],
['Barley', 'Jo', 'جو'],
['Lentil', 'Adas', 'عدس'],
['Bean', 'Loobeeaa', 'لوبیا'],
['Chickpea', 'Nokhod', 'نخود'],
['Storm', 'Toofaan', 'طوفان'],
['Cold (Weather)', 'Sarmaa', 'سرما'],
['Illness', 'Beemaaree', 'بیماری'],
['(A) Patient', 'Beemaar', 'بیمار'],
['Drawing', 'Naghaashee', 'نقاشی'],
['Dawn', 'Sepeedeh', 'سپیده'],
['Humanity', 'Ensaaniat', 'انسانیت'],
['Other Than', 'Gheer Az', 'غیر از'],
['Adventure', 'Maajeraa', 'ماجرا'],
['Clock Hand', 'Aghrabeh', 'عقربه'],
['Smooth', 'Saaf', 'صاف'],
['Ready', 'Aamaadeh', 'آماده'],
['Was Supposed To Happen', 'Gharaar Bood', 'قرار بود'],
['Noon', 'Zohr', 'ظهر'],
['Turned Off (Light)', 'Khaamoosh', 'خاموش'],
['(A) Light', 'Cheraagh', 'چراغ'],
['Clock', 'Sa\'at Deevaaree', 'ساعت دیواری'],
['To Try', 'Saey', 'سعی کردن'],
['Successful', 'Movafagh', 'موفق'],
['Clever', ['Baahoosh', 'Zerang'], ['باهوش', 'زرنگ']],
['Sharp', 'Teez', 'تیز'],
['Same', 'Ayn', 'عین'],
['Owl', 'Joghd', 'جغد'],
['Skewer', 'Seekh', 'سیخ'],
['Pothole', 'Cheleh Chooleh', 'چاله چوله'],
['Wrinkle', 'Charook', 'چروک'],
['Crease', 'Cheen', 'چین'],
['Groove', 'Sheeaar', 'شیار'],
['Deep', 'Ameegh', 'عمیق'],
['Bone', 'Ostokhaan', 'استخوان'],
['Taste', 'Mazeh', 'مزه'],
['Hole', 'Sooraakh', 'سوراخ'],
['Head', ['Sar', 'Kaleh'], ['سر', 'کله']],
['Bald Head', 'Kaleh Taas', 'کله طاس'],
['Various', ['Goonaagoon', 'Jooraajoor'], ['گوناگون', 'جوراجور']],
['Professor', 'Aastaad', 'استاد'],
['Caricature', 'Kaareekaatoor', 'کاریکاتور'],
['To Study', 'Dars Khaandan', 'درس خواندن'],
['Lesson', 'Dars', 'درس'],
['I am studying', 'Man dars mikhaanam', 'من درس میخوانم'],
['Office', ['Edaareh', 'Daftar'], ['اداره', 'دفتر']],
['Pencil', 'Madaad', 'مداد'],
['I Hope', 'Omeedvaaram', 'امیدوارم'],
['To Gaze', 'Zol Zadan', 'زل زدن'],
['Hole', 'Sooraakh', 'سوراخ'],
['Cake', 'Keyk', 'کیک'],
['Pickled Cucumbers', 'Kheeaar Shoor', 'خیار شور'],
['(A) Slice', 'Ghaach', 'قاچ'],
['Salami', 'Salaamee', 'سلامی'],
['Boiled Sweets', 'Aab Nabaat', 'آب نبات'],
['Cherry', 'Geelaas', 'گیلاس'],
['Pie', 'Paaee', 'پای'],
['Sausage', 'Sosees', 'سوسیس'],
['Chubby (Cute)', 'Topl O Mopl', 'تپل و مپل'],
['Cocoon', 'Peeleh', 'پیله'],
['Remained', ['Moond', 'Maandeh Bood'], ['موند', 'مانده بود']],
['Chewed', 'Javeed', 'جوید'],
['University', 'Daaneshgaah', 'دانشگاه'],
['Duck', 'Ordak', 'اردک'],
['Frog', 'Ghoorbaagheh', 'قورباغه'],
['Hippopotamus', 'Asb Aabee', 'اسب آبی'],
['Shark', 'Kooseh', 'کوسه'],
['Dental Floss', 'Nakh Dandaan', 'نخ دندان'],
['It\'s Very Enjoyable', 'Kheili Kayf Daareh', 'خیلی کیف داره'],
['In Motion', 'Dar Harket', 'در حرکت'],
['Remained', 'Maandeh', 'مانده'],
['Stayed In Place', 'Jaa Maandeh', 'جا مانده'],
['Hidden From View', 'Az Nezar Penhaan', 'از نظر پنهان'],
['Hidden', 'Penhaan', 'پنهان'],
['Inside', 'Daakhel', 'داخل'],
['To Jump', 'Pareedan Kardan', 'پریدن کردن'],
['Clown', 'Dalghak', 'دلقک'],
['Shrimp', 'Meygoo', 'میگو'],
['Jellyfish', 'Chatr-e Dareeaaee', 'چتر دریایی'],
['Squid', 'Maaheeye Morakab', 'ماهی مرکب'],
['Ocean', 'Ogheeaanoos', 'اقیانوس'],
['Octopus', 'Hashtpaa', 'هشتپا'],
['Whale', 'Nahang', 'نهنگ'],
['Bedroom', 'Otaagh Khaab', 'اطاق خواب'],
['I Can', 'Man Meetoonam', 'من میتونم'],
['I Am Smelling', 'Man Boo Mikonam', 'من بو می کنم'],
['I Am Tasting', 'Man Meechesham', 'من میچشم'],
['I Am Touching', 'Man Lams Mikonam', 'من لمس میکنم'],
['Balloon', 'Baadkonak', 'بادکنک'],
['Painting', 'Taabloo', 'تابلو'],
['Glove', 'Dastkesh', 'دستکش'],
['Brush', 'Boros', 'برس'],
['Bellybutton', 'Naaf', 'ناف'],
['Curious', 'Konjkaav', 'کنجکاو'],
['Headache', 'Sardard', 'سردرد'],
['Faeces', 'Madfooh', 'مدفوع'],
['Throne', 'Arsh', 'عرش'],
['Fireman', 'Mamoore Aatish Neshaanee', 'مامور آتش نشانی'],
['Station', 'Aeestgaah', 'ایستگاه'],
['Tractor', 'Teraaktoor', 'تراکتور'],
['Museum', 'Moozeh', 'موزه'],
['Scientist', 'Daaneshmand', 'دانشمند'],
['Chef', 'Aashpaz', 'آشپز'],
['Plumber', 'Loolehkesh', 'لوله کش'],
['Baker', 'Noonvaa', 'نونوا'],
['Thief', 'Dozd', 'دزد'],
['Pirate', 'Dozd-e Dareeaaee', 'دزد دریایی'],
['Acrobat', 'Aakroobaat', 'آکروبات'],
['Employee', 'Kaarmand-e Sherkat', 'کارمند شرکت'],
['Boss', 'Rayees', 'رئیس'],
['I Have An Accent', 'Man Lahjeh Daaram', 'من لهجه دارم'],
['I Am Joking', 'Shookhee Mikonam', 'شوخی میکنم'],
['Food Poisoning', 'Masmoomeeat Ghazaaee', 'مسمومیت غذایی'],
['Hungary', 'Majaarestaan', 'مجارستان'],
['Hobby', 'Sargarmee', 'سرگرمی'],
['(A) Stew', 'Khoresht', 'خورشت'],
['(Good) Sense', 'Sho\'oor', 'شعور'],
['Earmuffs', 'Roogoosheehaa', 'روگوشی ها'],
['Belief', 'Baavar', 'باور'],
['I Can\'t Believe It', 'Baavaram Nemishe', 'باورم نمیشه'],
['Digit', 'Adad', 'عدد'],
['Brawl', 'Janjaal', 'جنجال'],
['Wait!', 'Sabr Kon', 'صبر کن!'],
['Guest', 'Mehmaan', 'مهمان'],
['You Look Pale', 'Ranget Pareedeh', 'رنگت پریده'],
['Motorbike', 'Motoorseeklet', 'موتورسیکلت'],
['Complete (Full)', 'Kaamel', 'کامل'],
['Greedy', 'Harees', 'حریص'],
['Bottle', 'Botree', 'بطری'],
['Signature', 'Emzaa', 'امضا'],
['Religion', 'Deen', 'دین'],
['Lie', 'Doroogh', 'دروغ'],
['Doctor', 'Pezeshk', 'پزشک'],
['Constipation', 'Yoboosat', 'یبوست'],
['Diarrhoea', 'Es-haal', 'اسهال'],
['Fridge', 'Yakhchaal', 'یخچال'],
['(A) Giant', 'Ghool', 'غول'],
['Excellency (Sir)', 'Jenaab', 'جناب'],
['Bless You!', 'Aafeeat Baasheh', 'عافیت باشه'],
['Before', ['Peesh Az', 'Ghabl'], ['پیش از', 'قبل']],
['Effect', 'Asar', 'اثر'],
['Shhh!', 'Hees!', 'هیس!'],
['Spot / Mole', 'Khaal', 'خال'],
['Protection', 'Hafez', 'حفظ'],
['Finally', ['Belakhareh', 'Saranjaam'], ['بالاخره', 'سرانجام']],
['That\'s That', 'Eenam Az Een', 'اینم از این'],
['Celebration', 'Jashn', 'جشن'],
['Sleeve', 'Aasteen', 'آستین'],
['Tear (Drop)', 'Ashk', 'اشک'],
['Mint', 'Na\'naah', 'نعناع'],
['Traveller', 'Mosaafer', 'مسافر'],
['Travel', 'Mosaaferat', 'مسافرت'],
['Noble / Decent', 'Najeeb', 'نجیب'],
['Madam', 'Sarkaar-e Khanoom', 'سرکار خانم'],
['Politician', 'Seeaasatmadaar', 'سیاستمدار'],
['Hypocrisy', 'Reeaa', 'ریا'],
['Ruler (Drawing)', 'Khatkesh', 'خط کش'],
['Turnip', 'Shalgham', 'شلغم'],
['Schedule', 'Barnaameh', 'برنامه'],
['Throat', 'Goloo', 'گلو'],
['Lipstick', 'Maateek', 'ماتیک'],
['(A) Sail', 'Baadbaan', 'بادبان'],
['Blanket', 'Patoo', 'پتو'],
['Disinfectant', 'Zede Ofoonee', 'ضد عفونی'],
['Infection', 'Ofoonat', 'عفونت'],
['(A) Nap', 'Chort', 'چرت'],
['I Am Napping', 'Chort Meezanam', 'چرت میزنم'],
['I Napped', 'Chort Zadam', 'چرت زدم'],
['Islamic Republic', 'Jomhooree-ye Eslaamee', 'جمهوری اسلامی'],
['Tail', 'Dom', 'دم'],
['Naughty', 'Balaa', 'بلا'],
['Eloquent', 'Khosh Zabaan', 'خوش زبان'],
['Fingernail', 'Naakhoon', 'ناخن'],
['Moody', 'Akhmoo', 'اخمو'],
['Posse', 'Ekeep', 'اکیپ'],
['(Too) Salty', 'Shoor', 'شور'],
["Don't Worry", 'Negaraan Nabaash', 'نگران نباش'],
['Soil', 'Khaak', 'خاک'],
['Festivity', 'Ayd', 'عید'],
['Prayer', 'Do-aa', 'دعا'],
['Peace', 'Solh', 'صلح'],
['Amen', 'Aameen', 'امین'],
['Magic', 'Jaadoo', 'جادو'],
['I Am Betting', 'Shart Mikonam', 'شرط میکنم'],
['Shorts', 'Shalvaarak', 'شلوارک'],
['The First Time', 'Avaleen Baar', 'اولین بار'],
['Envelope', 'Paakat', 'پاکت'],
['The Boy Who Lived', 'Pesaree Keh Zendeh Maand', 'پسری که زنده ماند'],
['After / Since', 'Sepas', 'سپس'],
['Scream', 'Sedaaye Jeegh', 'صدای جیغ'],
['In The Direction (Of)', 'Beh Samt(e)', 'به سمت'],
['Loose', 'Goshaad', 'گشاد'],
['In Two Minds', 'Too Do Delam', 'تو دو دل'],
['Useful', 'Mofeed', 'مفید'],
['Greenhouse', 'Golkhaaneh', 'گلخانه'],
['Alcove', 'Taaghcheh', 'تاقچه'],
['Stop It!', 'Bas Kon', 'بس کن'],
['Shiny', 'Baraagh', 'براق'],
['Medium (Size)', 'Motavaset', 'متوسط'],
['Broom', 'Jaaroo', 'جارو'],
['Gizzard', 'Sangdoon', 'سنگدان'],
['Enemy', ['Doshman', 'Adoo'], ['دشمن', 'عدو']],
['Beetle', 'Soosk', 'سوسک'],
['Emptyheaded', 'Kaleh Pook', 'کله پوک'],
['Wizard', 'Jaadoogar', 'جادوگر'],
['King', 'Paadeshaah', 'پادشاه'],
['Sour Cherry', 'Aalbaloo', 'آلبالو'],
['Thunder & Lightning', 'Rad O Bargh', 'رعد و برق'],
['Noise', 'Sar O Sedaa', 'سر و صدا'],
['Chimney', 'Doodkesh', 'دودکش'],
['Photographer', 'Akkaas', 'عکاس'],
['Tuna', 'Maahee Ton', 'ماهی تن'],
['Vacuum Cleaner', 'Jaaroo Barghee', 'جارو برقی'],
['Bracelet', 'Dast Band', 'دست بند'],
['Necklace', 'Gardan Band', 'گردن بند'],
['Cash', 'Pool-e Naghd', 'پول نقد'],
['Minced Meat', 'Goosht-e Charkh Kardeh', 'گوشت چرخ کرده'],
['I Am Giving', 'Meedaham', 'می دهم'],
['I Gave', 'Daadam', 'دادم'],
['I Am Taking', 'Meegeeram', 'می گیرم'],
['I Took', 'Gereftam', 'گرفتم'],
['I Am Drinking', 'Meenoosham', 'می نوشم'],
['I Drank', 'Noosheedam', 'نوشیدم'],
['I Heard', 'Sheneedam', 'شنیدم'],
['I Am Running', 'Meedavam', 'می دوم'],
['I Ran', 'Daveedam', 'دویدم'],
['I Am Wearing', 'Meepoosham', 'می پوشم'],
['I Wore', 'Poosheedam', 'پوشیدم'],
['I Am Buying', 'Meekharam', 'می خرم'],
['I Bought', 'Khareedam', 'خریدم'],
['I Am Sitting', 'Meenesheenam', 'می نشینم'],
['I Sat', 'Neshastam', 'نشستم'],
['Classmate', 'Hamkelaasee', 'همکلاسی'],
['Surname', 'Esm-e Faameel', 'اسم فامیل'],
['List', 'List', 'لست'],
['Come This Way Please', 'Az Een Taraf Lotfan', 'از این طرف لطفآ'],
['Fringe', 'Chatree', 'چتری'],
['It Looks Delicious', 'Khoshmazeh Be Nazar Miresad', 'خوشمزه به نظر میرسد'],
['Do You Know English?', 'Ingelisi Baladeed?', 'اینگلیسی بلدید'],
['I Am Going', ['Meeravam', 'Meeram'], ['می روم', 'می رم']],
['I Went', 'Raftam', 'رفتم'],
['Holiday', "Ta'teelaat", 'تعطیلات'],
['Simple / Easy', 'Saadeh', 'ساده'],
['(A) Nurse', 'Parastaar', 'پرستار'],
[['Headteacher', 'Manager'], 'Modeer', 'مدیر'],
['Spinach', 'Esfanaaj', 'اسفناج'],
['Lake', 'Dareeaacheh', 'دریاچه'],
['I Am Coming', 'Meeaam', 'میام'],
['I Came', 'Aamadam', 'آمدم'],
['Come With Me', 'Baa Man Beeaaeed', 'با من بیاید'],
['I Knew', 'Meedaanestam', 'میدانستم'],
['I Am Seeing', 'Meebeenam', 'می بینم'],
['I Saw', 'Deedam', 'دیدم'],
['I Wanted', 'Khaastam', 'خواستم'],
['I Want', 'Meekhaahm', 'می خواهم'],
['I Asked', 'Porseedam', 'پرسیدم'],
['I Am Asking', 'Meeporsam', 'میپرسم'],
['Jewish', 'Yahoodee', 'یهودی'],
['Muslim', 'Mosalmaan', 'مسلمان'],
['Zoroastrian', 'Zartoshtee', 'زرتشتی'],
['Fresh', 'Taazeh', 'تازه'],
['Painter', 'Naghaash', 'نقاش'],
['Several', 'Chandeen', 'چندین'],
['Tomb', 'Aaraamgaah', 'آرامگاه'],
['Shrine', 'Zeeaaratgaah', 'زیارتگاه'],
['Very', 'Beseeaar', 'بسیار'],
['(A) Length / Duration', 'Tool', 'طول'],
['Manufacturing / Construction', 'Saakht', 'ساخت'],
['I Am Celebrating', 'Jashn Meegeeram', 'جشن میگیرم'],
['I Celebrated', 'Jashn Gereftam', 'جشن گرفتم'],
['Congratulation', 'Tabreek', 'تبریک'],
['Meet And Greet / Visiting', 'Deed O Baazdeed', 'دید و بازدید'],
['Twins', 'Dogholoo', 'دوقلو'],
['Is Situated', 'Gharaar Daarad', 'قرار دارد'],
['Cool / Lively / Spirited', 'Baahaal', 'باحال'],
['Evidence / Proof / Uni Degree', 'Madrak', 'مدرک'],
['Gambler', 'Ghomaar Baaz', 'قمار باز'],
['Womaniser', 'Zan Baaz', 'زن باز'],
['Handicrafts', 'Sanaayeh Dastee', 'صنایع دستی'],
['Idiot', "Beesho'oor", 'بیشعور'],
['To Change / Exchange', 'Avaz Kardan', 'عوض کردن'],
['(A) Choice', 'Entekhaab', 'انتخاب'],
['I Am Choosing', 'Daaram Entehaab Meekonam', 'دارم انتخاب میکنم'],
['I Chose', 'Entekhaab Kardam', 'انتخاب کردم'],
['Black', 'Meshkee', 'مشکی'],
[['Closed', 'Packet'], 'Basteh', 'بسته'],
['(The) Remains', 'Baaghee', 'باقی'],
['Electric Kettle', 'Ketree Barghee', 'کتری برقی'],
['(A) Laundry', 'Rakhtshooeekhaaneh', 'رختشویخانه'],
["There's No Difference", 'Fargh Nadaareh', 'فرق نداره'],
['Overeating', 'Porkhooree', 'پرخوری'],
['Air-Conditioner', 'Kooler', 'کولر'],
['(A) Guide', 'Raahnamaa', 'راهنما'],
['Ground Floor', 'Tabaghe Hamkaf', 'طبقه همکف'],
['Mobile Phone', 'Telefon-e Hamraah', 'تلفن همراه'],
['Makeup', 'Aaraayesh', 'آرایش'],
['I Searched', 'Gashtam', 'گشتم'],
['I\'m Sure', 'Motmaennam', 'مطمئنم'],
['No (Actually)', 'Kheyr', 'خیر'],
['Sitting Room', 'Otaagh Nesheeman', 'اتاق نشیمن'],
['Quiet', ['Saaket', 'Aaraam'], ['ساکت', 'آرام']],
['Staring', 'Kheereh', 'خیره'],
['I Would Prefer If', 'Tarjeeh Meedaham Ke', 'ترجیح میدهم که'],
['Shape', 'Shekl', 'شکل'],
['Cleric', 'Aakhoond', 'آخوند'],
['Tattoo', 'Khaal Koobee', 'خال کوبی'],
['Forecast', 'Peesh Beenee', 'پیش بینی'],
['Road', ['Jaaddeh', 'Kheeaabaan'], ['جاده', 'خیابان']],
['Jesus', 'Eesaa', 'عیسی'],
['Fish Bowl', 'Tong-e Maahee', 'تنگ ماهی'],
[['Sequin', 'Fish Scale'], 'Poolak', 'پولک'],
['Vase', 'Goldaan', 'گلدان'],
['Faraway', 'Doordast', 'دوردست'],
['Stretch (A Thing) Out', 'Deraaz Kardan', 'دراز کردن'],
['Pony', 'Taatoo', 'تاتو'],
['Load / Cargo', 'Baar', 'بار'],
['Early Riser', 'Sahar Kheez', 'سحرخیز'],
['Addict', "Mo'taad", 'معتاد'],
['Pen', ['Khodkaar', 'Ghalam'], ['قلم', 'خودکار']],
['Dish', 'Zarf', 'ظرف'],
['To Rest', 'Esteraahat Kardan', 'استراحت کردن'],
[['Task', 'Homework'], 'Takleef', 'تکلیف'],
['To Decorate', 'Tazeeeen Kardan', 'تزیین کردن'],
['Thumb', 'Shast', 'شست'],
['I Am Washing', 'Meeshooram', 'می شورم'],
['Materialistic', 'Maadeegaree', 'مادیگری'],
['Fever', 'Tab', 'تب'],
['Village', ['Roostaa', 'Dehaat'], ['روستا', 'دهات']],
['Prevalent', 'Raayej', 'رایج'],
['Valuable', 'Baa Arzesh', 'با ارزش'],
['Rich (In)', 'Ghanee', 'غنی'],
['Careful', 'Movaazeb', 'مواظب'],
['Be Careful', 'Movaazeb Baash', 'مواظب باش'],
['Reception Room', 'Otaagh-e Pazeeraaee', 'اتاق پذیرای'],
['Laminated', 'Paarket', 'پارکت'],
['Washing Machine', 'Maasheen-e Lebaasshooee', 'ماشین لباسشویی'],
['Budget', 'Boodjeh', 'بودجه'],
['Genius', 'Naabegheh', 'نابغه'],
['Dishwasher', 'Maasheen-e Zarfshooee', 'ماشین ظرفشویی'],
['Congratulations', 'Aafareen', 'آفرین'],
['Luckily', 'Khoshbakhtaaneh', 'خوشبختانه'],
['Close Friend', 'Doost-e Sameemee', 'دوست صمیمی'],
['Real Name', 'Esm-e Aslee', 'اسم اصلی'],
['Song', ['Aavaaz', 'Aahang', 'Taraaneh'], ['آواز', 'آهنگ', 'رهگذر']],
['In My Opinion', 'Beh Nazar-e Man', 'به نظر من'],
['Good For You', 'Khosh Be Haal-e Shomaa', 'خوش به حالت'],
['The Day After Tomorrow', 'Pas Fardaa', 'پس فردا'],
['What Day Is It Today?', 'Emrooz Chand Shanbast', 'امروز چند شنبه است'],
['Player (Sport)', 'Baazeekon', 'بازیکن'],
['Rainbow', 'Rangeen Kamoon', 'رنگین کمون'],
['Light Switch', 'Keleed-e Bargh', 'کلید برق'],
['(A) Slide', 'Sarsareh', 'سرسره'],
["There Wasn't Space To Drop A Needle", 'Jaaye Soozan Aandaakhtan Nabood', 'جای سوزن انداختن نبود'],
['Cancer', 'Sarataan', 'سرطان'],
['Asthma', 'Aasm', 'آسم'],
['To Fast', 'Roozeh Gereftan', 'روزه گرفتن'],
['Teeny-Weeny', 'Reezeh Meezeh', 'ریزه میزه'],
['Large', 'Dorosht', 'درشت'],
['Microscopic', 'Zareh Beenee', 'ذره بینی'],
['Exactly', 'Dagheeghaa', 'دقیقا'],
['Cream', 'Khaameh', 'خامه'],
['(Food) Order', 'Sefaaresh', 'سفارش'],
['Turkey (Food)', 'Booghalamoon', 'بوقلمون'],
['Apricot', 'Zardaaloo', 'زردآلو'],
['Menstruation', 'Heyz', 'حیض'],
['Glue', 'Chasb', 'چسب'],
['Jelly', 'Zheleh', 'ژله'],
['Nose', ['Beenee', 'Damaagh'], ['بینی', 'دماغ']],
['Boat', 'Ghaayegh', 'قایق'],
['Sugar Cube', 'Ghand', 'قند'],
['Henhouse', 'Morghdaaree', 'مرغداری'],
['Cooking Oil', 'Roghan', 'روغن'],
['I Know', 'Man Meedaanam', 'من می دانم'],
['I Knew', 'Man Meedaanestam', 'من می دانستم'],
['Around The World', 'Beh Door-e Donyaa', 'به دورِ دنیا'],
['Ship', 'Kashti', 'کشتی'],
['I Am Teaching', 'Yaad Meedaham', 'یاد میدهم'],
['I Taught', 'Yaad Daadam', 'یاد دادم'],
['I Was Teaching', 'Yaad Meedaadam', 'یاد می دادم'],
['Tasteless / Boring', 'Beemazeh', 'بیمزه'],
['Debtor', 'Bedehkaar', 'بدهکار'],
['Cottage', 'Kolbeh', 'کلبه'],
['Field', 'Keshtzaar', 'کشتزار'],
['To Cultivate', 'Kesht Kardan', 'کشت کردن'],
['To Be Paid', 'Dastmozd Gereftan', 'دستمزد گرفتن'],
['To Feel', 'Hes Kardan', 'حس کردن'],
['Purpose / Intent', 'Manzoor', 'منظور'],
['Thank God', 'Shokr-e Khodaa', 'شکر خدا'],
['Glorious', 'Baashokooh', 'باشکوه'],
['I Am Shy', 'Man Khejaalatee Hastam', 'من خجالتی هستم'],
['Happy', 'Shaad', 'شاد'],
['To Take (Future He/She/It)', 'Bebarad', 'ببرد'],
[['Furniture', 'Stuff'], 'Vasaayel', 'وسایل'],
['Technology', 'Fanaavaree', 'فناوری'],
['To Use', 'Estefaadeh Kardan', 'استفاده کردن'],
['Boring', 'Kesel Konandeh', 'کسل کننده'],
['Some (A Few)', 'Ba\'zee', 'بعضی'],
['Special / Specific', 'Khaas', 'خاص'],
['Special', 'Veezheh', 'ویژه'],
['Especially', 'Beh Veezheh', 'به ویژه'],
['To Waste', 'Talaf Kardan', 'تلف کردن'],
['Waste (Noun)', 'Etlaaf', 'اتلاف'],
['Waste Of Time', 'Etlaaf-e Vaght', 'اتلافِ وقت'],
['Waiting', 'Montazer', 'منتظر'],
['I Am Standing', 'Mee-eestam', 'می ایستم  '],
['I Am Waiting', 'Montazer Hastam', 'منتظر هستم'],
['Button (Clothes & Pushable)', 'Dokmah', 'دکمه'],
['How (Formal)', 'Chegooneh', 'چگونه'],
['I Started', 'Aaghaaz Kardam', 'آغاز کردم'],
['I Am Starting', 'Aaghaaz Meekonam', 'آغاز می کنم'],
['Rowing Boat', 'Ghaayegh-e Paarooyee', 'قایقِ پارویی'],
['Sailing Boat', 'Ghaayegh-e Baadbaanee', 'قایقِ بادبانی'],
['Adventurous', 'Por Maajaraa', 'پرماجرا'],
['Companion', ['Hamsafar', 'Hamraah'], ['همسفر', 'همراه']],
['Crocodile', 'Temsaah', 'تمساح'],
['Port (Sea)', 'Bandar', 'بندر'],
['Also', 'Hamcheneen', 'همچنین'],
['Portugal', 'Porteghaal', 'پرتغال'],
['Orange (Fruit)', 'Portaghaal', 'پرتقال'],
['The Remaining / The Rest', 'Bagheeyeh', 'بقیه'],
[['History (Subject)', 'Date'], 'Taareekh', 'تاریخ'],
['Have Fun', 'Khosh Begzareh', 'خوش بگذره'],
['Say Hi To Your Father', 'Beh Pedaretaan Salaam Beresaaneed', 'به پدرتان سلام برسانید'],

['To Travel A Distance', 'Tey Kardan', 'طی کردن'],
['To Pass (By / Through) (Challenging)', 'Oboor Kardan', 'عبور کردن'],
['To Start Moving (Somewhere)', 'Harekat Kardan', 'حرکت کردن'],

['I Passed', 'Gozashtam', 'گذشتم'],
['I Am Passing', 'Man Meegozaram', 'من میگذرم'],
['I Was Passing', 'Man Meegozashtam', 'من می گذشتم'],

['To Traverse (Road/Path)', 'Peymoodan', 'پیمودن'],
['I Traversed (Road/Path)', 'Man Peymoodam', 'من پیمودم'],
['I Was Traversing (Road/Path)', 'Man Meepeymoodam', 'من می پیمودم'],
['I Am Traversing (Road/Path)', 'Man Meepeymaayam', 'من می پیمایم'],

['To Continue', 'Edaameh Daadan', 'ادامه دادن'],
['I Am Continuing', 'Edaameh Meedaham', 'ادامه می دهم'],
['I Continued', 'Edaameh Daadam', 'ادامه دادم'],
['I Was Continuing', 'Edaameh Meedaadam', 'ادامه می دادم'],

[['Reader', 'Singer'], 'Khaanandeh', 'خواننده'],

['Marriage', 'Ezdevaaj', 'ازدواج'],
['Flowing', 'Ravaan', 'روان'],
['Permanent', 'Daaem', 'دائم'],
['Unless', 'Magar', 'مگر'],
['Salary', 'Hoghoogh', 'حقوق'],
['Architect', 'Me-maar', 'معمار'],
['Valley', 'Dareh', 'دره'],
['Side', 'Samt', 'سمت'],
['Pencil Sharpener', 'Taraash', 'تراش'],
['To Sew', 'Dookhtan', 'دوختن'],
['Skirt', 'Daaman', 'دامن'],
['To Design', 'Tarh Kardan', 'طرح  کردن '],
['I Could', 'Tavaanestam', 'توانستم'],
['Trumpet', 'Sheypoor', 'شیپور'],
['Forever', 'Taa Abad', 'تا ابد'],
['Peasant', 'Rayeat', 'رعیت'],
['Poverty', 'Faghr', 'فقر'],
['To Crush', 'Leh Kardan', 'له کردن'],
['Deer', 'Aahoo', 'آهو'],
['Court', 'Daadgaah', 'دادگاه'],
['Purple', 'Banafsh', 'بنفش'],
['Tulip', 'Laaleh', 'لاله'],
['Season', 'Fasl', 'فصل'],
['Owner', 'Saaheb', 'صاحب'],
['Direction', 'Jahat', 'جهت'],
['Infamous / Shamed', 'Rasvaa', 'رسوا'],
['Crowd / The Masses', 'Jamaa-at', 'جماعت'],
['Pear', 'Golaabee', 'گلابی'],
['Dragonfly', 'Sanjaaghak', 'سنجاقک'],
['Too', 'Neez', 'نیز'],
['Daffodil', 'Narges', 'نرگس'],
['If You Don\'t Want To Be Shamed, Become The Colour Of Society', 'Khaahee Nashavee Rasvaa, Hamrang-e Jamaa-at Sho', 'خواهی نشوی رسوا همرنگ جماعت شو '],
['Severe', 'Shadeed', 'شدید'],
['Martyr', 'Shaheed', 'شهید'],
['Interview', 'Mosaahebeh', 'مصاحبه'],
['Hurry', 'Ajaleh', 'عجله'],
['Telescope', 'Doorbeen Nejoomee', 'دوربین نجومی'],
['Temptation', 'Vasvaseh', 'وسوسه'],
['Primrose', 'Paamchaal', 'پامچال'],
['Sunset', 'Ghoroob', 'غروب'],
['Prostitute', 'Faahesheh', 'فاحشه'],
['Criterion', 'Melaak', 'ملاک'],
['Slow', ['Kond', 'Yavaash', 'Aahesteh'], ['کند', 'یواش', 'اهسته']],
['Outcome', 'Payaamad', 'پیامد'],
['Result', 'Nateejeh', 'نتیجه'],
['Single (Relationship)', 'Mojarad', 'مجرد'],
['Musical Instrument', 'Saaz', 'ساز'],
["Maybe", "Shaayad", "شاید"],
['To See Someone Off', 'Badragheh Kardan', 'بدرقه کردن'],
['Answer', ['Paasokh', 'Javaab'], ['پاسخ', 'جواب']],
['Dice', 'Taas', 'تاس'],
['(Ice Cream) Cone', 'Gheef', 'قیف'],
['Silk', 'Abreesham', 'ابریشم'],
['Feather', 'Par', 'پر'],
['Hanging', 'Aaveezaan', 'آویزان'],
['Unaware', 'Ghaafel', 'غافل'],
['Horizontal', 'Ofoghee', 'افقی'],
['Vertical', 'Omoodee', 'عمودی'],
['Seashell', 'Sadaf', 'صدف'],
['Pile', 'Toodeh', 'توده'],
['Crime', 'Jorm', 'جرم'],
['Usually', 'Mamoolan', 'معمولا'],
['Exam', 'Emtehaan', 'امتحان'],
['Device', 'Vaseeleh', 'وسیله'],
['Passport', 'Gozarnaameh', 'گذرنامه'],
['Close It (Command)', 'Beband', 'ببند'],
['Topic', 'Mozooh', 'موضوع'],
['Roof', 'Baam', 'بام'],
['Calmly', 'Baa Khoonsardee', 'با خونسردی'],
['Bath', 'Vaan', 'وان'],
['Respectable', 'Mohtaram', 'محترم'],
['Doorman', 'Darbaan', 'دربان'],
['I Hear', 'Man Meeshnavam', 'من می شنوم'],
['Officer', 'Mamoor', 'مامور'],
['Handkerchief', 'Dastmaal', 'دستمال'],
['Penetrating Look', 'Negaahe Naafez', 'نگاه نافذ'],
['President', 'Rayees-e Jomhoor', 'رئیس جمهور'],
['Recently', 'Taazehgee', 'تازهگی'],
['House', ['Khaane', 'Manzel'], ['خانه', 'منزل']],
['Pressure', 'Feshaar', 'فشار'],
['Buggy', 'Kaaleskeh', 'کالسکه'],
['Appetite', 'Eshtehaa', 'اشتها'],
['Shaky', 'Larzaan', 'لرزان'],
['(One\'s) Honor', 'Sheraafat', 'شرافت'],
['Biting', 'Gaaz Gereftan', 'گاز گرفتن'],
['Face', ['Soorat', 'Chehreh'], ['صورت', 'چهره']],
['Oven', 'Ojaagh', 'اجاق'],
['Huge / Great', 'Azeem', 'عظیم'],
['Exaggeration', 'Eghraagh', 'اغراق'],
['Farm', 'Mazraeh', 'مزرعه'],
["To Be Amazed / Surprised", "Ta'job Kardan", "تعجّب کردن"],
['Award / Prize', 'Jaayezeh', 'جایزه'],
['Social', 'Ejtamaayee', 'اجتماعی'],
['(A) Show', 'Nemaayesh', 'نمایش'],
['Astronaut', 'Fazaanavard', 'فضانورد'],
['To Forget', 'Faraamoosh Kardan', 'فراموش کردن'],

];

//  ['', '', ''],
