var CARDS = [
['Fart',           'Gooz',           'گوز'],
['Cow',            'Gaav',           'گاو'],
['Dog',            'Sag',            'سگ'],
['Cat',            'Gorbeh',         'گربه'],
['Chair',          'Sandali',        'صندلی'],
['Table',          'Meez',           'میز'],
['Wood',           'Choob',          'چوب'],
['Bin',            'Zobaale Daanee', 'زباله دانی'],
['Plate',          'Bashghab',       'بشقاب'],
['Spoon',          'Ghashogh',       'قاشق'],
['Fork',           'Changol',        'چنگال'],
['Knife',          'Chaaghoo',       'چاقو'],
['Coat',           'Kot',            'کت'],
['Scarf (head)',   'Roosaree',       'روسری'],
['Scarf (neck)',   'Shaal',          'شال'],
['Bed',            'Takht',          'تخت'],
['Curtains',       'Parde',          'پرده'],
['Watch',          "Sa'at",          'ساعت'],
['Cupboard',       'Komod',          'کمد'],
['Socks',          'Jooraab',        'جوراب'],
['Jeans',          'Shalvare Jean',  'شلوار جین'],
['T-Shirt',        'T-Shirt',        'تی شرت'],
['Jewellery',      'Javaaher',       'جواهر'],
['Mouth',          'Dahan',          'دهان'],
['Face',           'Soorat',         'صورت'],
['Hair',           'Moo',            'مو'],
['Eye',            'Cheshm',         'چشم'],
['Window',         'Panjareh',       'پنجره'],
['Door',           'Dar',            'در'],
['House',          'Khaane',         'خانه'],
['Thing',          'Cheez',          'چیز'],
['Question',       'Soaal',          'سوال'],
['Country',        'Keshvar',        'کشور'],
['School',         'Madrese',        'مدرسه'],
['Year',           'Saal',           'سال'],
['Company',        'Sherkat',        'شرکت'],
['Number',         'Shomareh',       'شماره'],
['Room',           'Otaagh',         'اتاق'],
['Reality',        'Vaaghayiat',     'واقعیت'],
['Job',            'Kaar',           'کار'],
['Shoe',           'Kafsh',          'کفش'],
['Grey',           'Khakestaree',    'خاکستری'],
['Neck',           'Gardan',        'گردن'],
['Chest',          'Seene',          'سینه'],
['Chin',           'Chaane',         'چانه'],
['Heart',          'Ghalb',          'قلب'],
['Least',          'Kamtarin',       'کمترین'],
['Sleep',          'Khaab',          'خواب'],
['Dream',          'Rooeea',        'رویا'],
['Good',           'Khoob',          'خوب'],
['New',            'Jadeed',         'جدید'],
['First',          'Aval',           'اول'],
['Last',           'Akhar',          'آخر'],
['Old (Thing)',    'Ghadeemee',      'قدیمی'],
['Correct',        'Dorost',         'درست'],
['Big',            'Bozorg',         'بزرگ'],
['Tall',           'Ghadboland',     'قد بلند'],
['Short',          'Kootah',         'کوتاه'],
['Learn',          'Yaadgiree',     'یادگیری'],
[['Long', 'High', 'Loud'], 'Boland', 'بلند'],
['Low',            'Paeeeen',        'پایین'],
['Different',      'Mokhtalef',      'مختلف'],
['Next',           'Ba-d',           'بعد'],
['Early',          'Zood',           'زود'],
['Young',          'Javaan',         'جوان'],
['Important',      'Mohem',          'مهم'],
['Public',         'Omoomee',        'عمومی'],
['Private',        'Khosoosee',      'خصوصی'],
['Under',          'Ziir',           'زیر'],
['Above',          'Baala',          'بالا'],
['Heavy',          'Sangeen',        'سنگین'],
['Light (Weight)', 'Sabok',          'سبک'],
['Weak',           "Za'eef",         'ضعیف'],
['Strong',         'Ghavee',         'قوی'],
['Rude',           'Beeaadab',       'بی ادب'],
['Polite',         "Moa'dab",        'مودب'],
['Most',           'Bishtarin',      'بیشترین'],
['Follow',         'Donbaal Kardan', 'دنبال کردن'],
['Tree',           'Derakht',        'درخت'],
['Sea',            'Dareeah',        'دریا'],
['Ceiling',        'Saghf',          'سقف'],
['Bottom',         ['Kaf', 'Ta'],    ['کف','ته']],
['Stairs',         'Peleh',          'پله'],
['Train',          'Ghataar',        'قطار'],
['Danger',         'Khatar',         'خطر'],
['Horse',          'Asb',            'اسب'],
['Mouse',          'Moosh',          'موش'],
['Fish',           'Maahi',          'ماهی'],
['Puppy',          'Toole Sag',      'توله سگ'],
['Sheep',          'Goosfand',       'گوسفند'],
['Lamb (Animal)',  'Bar-e',          'بره'],
['Lamb (Food)',    'Gooshte Bar-e',  'گوشت بره'],
['Chicken',        'Jooje',          'جوجه'],
['Hen',            'Morgh',          'مرغ'],
['Pig',            'Khook',          'خوک'],
['Pork',           'Goosht-e Khook', 'گوشت خوک'],
['Rabbit',         'Khargoosh',      'خرگوش'],
['Forehead',       'Peeshaanee',     'پیشانی'],
['Dictionary',     'Ketaab Tarjome', 'کتاب ترجمه'],
['Apple',          'Seeb',           'سیب'],
['Orange (Fruit)', 'Portaghaal',     'پرتقال'],
['Egg',            'Tochm-e Morg',   'تخم مرغ'],
['Banana',         'Moz',            'موز'],
['Pineapple',      'Anaanaas',       'اناناس'],
['Nectarine',      'Shaleel',        'شلیل'],
['Olive',          'Zeetoon',        'زیتون'],
['Pistachio',      'Peste',          'پسته'],
['Rice (Cooked)',  'Polo',           'پلو'],
['Rice (Uncooked)','Berenj',         'برنج'],
['Hat',            'Kaala',          'کلاه'],
['Ham',            'Zhambon',        'ژامبون'],
['Vegetable',      'Sabzee',         'سبزی'],
['Fruit',          'Meeve',          'میوه'],
['Aftenoon',       'Asr',            'عصر'],
['Walking',        'Rah Raftan',     'راه رفتن'],
['Running',        'Daveedan',       'دویدن'],
['Laughter',       'Khande',         'خنده'],
['Cry',            'Ger-ye',         'گریه'],
['Cheek',          'Goon-e',         'گونه'],
['Kind',           'Mehrabaan',      'مهربان'],
['Cruel',          'Beerahm',        'بی رحم'],
['Funny',          'Khande Daar',    'خنده دار'],
['Arm',            'Dast',           'دست'],
['Tooth',          'Dandaan',        'دندان'],
[['Tongue', 'Language'],         'Zabaan',         'زبان'],
['Stupid',         'A-hmagh',        'احمق'],
['Open',           'Baaz',           'باز'],
['Closed',         'Bast-e',         'بسته'],
['Teacher',        'Mohalem',        'معلم'],
['Mountain',       'Kooh',           'کوه'],
['Monster',        'Heyoolah',       'هیولا'],
['Brain',          'Maghz',          'مغز'],
['Glasses',        'Aeenak',         'عینک'],
['Rain',           'Baaraan',        'باران'],
['Cloud',          'Abr',            'ابر'],
['Spring (Season)','Bahaar',         'بهار'],
['Summer',         'Taabestaan',     'تابستان'],
['Autumn',         'Paaeeeez',       'پاییز'],
['Winter',         'Zamestaan',      'زمستان'],
['Wedding',        'Aroosee',        'عروسی'],
['Poet',           'Shaaer',         'شاعر'],
['Poem',           'Shehr',          'شعر'],
['Healthy',        'Saalem',         'سالم'],
['Sad',            'Ghamgeen',       'غمگین'],
['Tight',          'Tang',           'تنگ'],
['Loose',          'Shol',           'شل'],
['Pull',           'Kesheedan',      'کشیدن'],
['Push',           'Hol Daadan',     'هل دادن'],
['Hill',           'Tap-e',          'تپه'],
['Wind',           'Baad',           'باد'],
['Bag',            'Keef',           'کیف'],
['Carpet',         'Farsh',          'فرش'],
['Candle',         'Sham',           'شمع'],
['Fire',           'Aatish',         'آتش'],
['Swimming',       'Shenaa',         'شنا'],
['Hot',            'Daagh',          'داغ'],
['Thin (Weight)',  'Laaghar',        'لاغر'],
['Elevator',       'Aasaansaar',     'آسانسور'],
['Mirror',         'Ay-ne',          'اینه'],
['Smile',          'Labkhand',       'لبخند'],
['Bird',           'Parandeh',       'پرنده'],
['Downstairs',     'Tabaghe Paaeen', 'طبقه پایین'],
['Eating',         'Khordan',        'خوردن'],
['Drinking',       'Noosheedan',     'نوشیدن'],
['Empty',          'Khaalee',        'خالی'],
['Full',           'Por',            'پر'],
['Rich',           'Servatmand',     'ثروتمند'],
['Poor',           'Fagheer',        'فقیر'],
['Donkey',         'Khar',           'خر'],
['Ugly',           'Zesht',          'زشت'],
['Grass',          'Chaman',         'چمن'],
['Line',           'Khat',           'خط'],
['To Arrive',      'Reseedan',       'رسیدن'],
['Step',           ['Ghadam', 'Gaam'],         ['قدم', 'گام']],
['A Screw',        'Peech',          'پیچ'],
['Hopeless',       'Naa-omeed',      'ناامید'],
['Patience',       'Sabr',           'صبر'],
['Until',          'Taa',            'تا'],
['Snow',           'Barf',           'برف'],
['Sudden',         'Naagahaanee',    'ناگهانی'],
['Start',          'Shoroo',         'شروع'],
['Overflowing',    'Labreez',        'لبریز'],
['Dust',           'Ghobar',         'غبار'],
['Energy',         'Enerzhee',       'انرژی'],
['Silence',        'Sokoot',         'سکوت'],
['Daily',          'Roozaane',       'روزانه'],
['Take',           'Gereft',         'گرفت'],
['Pedestrian',     'Rahgozar',       'رهگذر'],
['Shadow',         'Saaye',          'سایه'],
['Moon',           'Maah',           'ماه'],
['Voice',          'Sedaa',          'صدا'],
['Song',           'Taraneh',        'ترانه'],
['Need',           'Neeaaz Daashtan','نیاز داشتن'],
['Old (Person)',   'Pee-r',          'پیر'],
['12',             'Davaazdeh',      'دوازده'],
[['Light (Colour)', 'Bright'],         'Roshan',         'روشن'],
['Grandchild',     'Naveh',          'نوه'],
['Around',         'D-oor',          'دور'],
['[Him/Her]self',  'Khodesh',        'خودش'],
['Total',          'Jamh',           'جمع'],
['Stream',         'Jooeebaar',      'جویبار'],
['Stone',          'S-ang',          'سنگ'],
['Wall',           'Diivaar',        'دیوار'],
['Flowing',        'Ravaan',         'روان'],
['Back (Behind)',  ['Posht', 'Aghab'], ['پشت', 'عقب']],
['Moss',           'Khaze',          'خزه'],
['Wallet / Purse', 'Keef-e Pool',    'کیف پول'],
['Handbag',        'Keef-e Dastee',  'کیف دستی'],
['Fist',           'Mosht',          'مشت'],
['Soldier',        'Sarbaaz',        'سرباز'],
['Crazy',          'Deevaaneh',      'دیوانه'],
['Foreigner',      'Khaarejee',      'خارجی'],
['Word',           'Kalameh',        'کلمه'],
['Brave',          'Shojaa',         'شجاع'],
['Happened',       'Shodeh',         'شده'],
['Moonlight',      'Mahtaab',        'مهتاب'],
['Their',          'Shaan',          'شان'],
['Fell',           'Aaftaad',        'افتاد'],
['Story',          ['Daastaan', 'Ghes-e'],       ['داستان', 'قصه']],
['Mixed',          'Ghaatee',        'قاتی'],
['Other',          'Digar',          'دیگر'],
['Put',            'Gozaasht',       'گذاشت'],
['Reluctance',     'Bee Maylee',     'بی میلی'],
['Side',           'Taraf',          'طرف'],
['Returned',       'Barmeegasht',    'برمیگشت'],
['Time',           ['Vaght', 'Daf\'eh'],          ['وقت', 'دفعه']],
['Imagination',    'Kheeaal',        'خیال'],
['Testicle',       'Bayz-e',         'بیضه'],
['Busy',           'Mashghool',      'مشغول'],
['Make',           'Dorost Kardan',  'درست کردن'],
['Thick',          'Koloft',         'کلفت'],
['Branch',         'Shakhe',         'شاخه'],
['Ear',            'Goosh',          'گوش'],
['Repeat',         'Tekraar',        'تکرار'],
['Pimp',           'Jaakesh',        'جاکش'],
['Level',          'Tabaghe',        'طبقه'],
['Box',            'Ja\'beh',        'جعبه'],
['To (Give) Promise', 'Ghol Daadan', 'قول دادن'],
['Circumcision',   'Khatne',         'ختنه'],
['Accident',       'Tasaadof',       'تصادف'],
['To Wake Up',     'Beedaar Kard',   'بیدار کرد'],
['Polluted',       'Alood-e',        'آلود'],
['Sleepy',         'Khaab Alood-e',  'خواب الود'],
['Now',            'Haalaa',         'حالا'],
['Skin',           'Poost',          'پوست'],
['Forest',         'Jangal',         'جنگل'],
['Interesting',    'Jaaleb',         'جالب'],
['Potato',         'Seeb Zameenee',  'سیب زمینی'],
['Earth',          'Zameen',         'زمین'],
['Onion',          'Peeaaz',         'پیاز'],
['Pomegranate',    'Anaar',          'انار'],
[['Spicy', 'Fast'], 'Tond',          'تند'],
['Reading',        'Khaandan',       'خواندن'],
['Circle',         'Daayere',        'دایره'],
['Square',         'Moraba-h',       'مربع'],
['Kick',           'Paazadan',       'پا زدن'],
['To Travel',      'Safar Kardan',   'سفر کردن'],
['Tower',          'Borj',           'برج'],
['Perfume',        'Atr',            'عطر'],
['Suitcase',       'Chamadaan',      'چمدان'],
['Fate',           'Ghesmat',        'قسمت'],
['Drunk',          'M-ast',          'مست'],
['Yet',            'Hanooz',         'هنوز'],
['Dark (Colour)',  'Teereh',         'تیره'],
['Rhino',          'Kargadan',       'کرگدن'],
['Stop!',          'Eest',           'ایست'],
['Sew your lips',  'Lab dooz',       'لب دوز'],
['Alas',           'Afsoos',         'افسوس'],
['Comfortable',    'Raahat',         'راحت'],
['Wheel',          'Charkh',         'چرخ'],
['Bike',           'Docharkhe',      'دوچرخه'],
['To Smoke',       'Dood Kardan',    'دود کردن'],
['Spider',         'Ankaboot',       'عنکبوت'],
['Saliva',         'Bozagh',         'بزاق'],
['Pillow',         'Baalesh',        'بالش'],
['Duvet',          'Lahaaf',         'لحاف'],
['Sky',            'Aasemaan',       'آسمان'],
['Against',        'Aley-he',        'علیه'],
['Prison',         'Zendaan',        'زندان'],
['Salt',           'Namak',          'نمک'],
['Sweet',          'Sheereen',       'شیرین'],
['Sour',           'Torsh',          'ترش'],
['Dagger',         'Khanjar',        'خنجر'],
['Together',       'Baa ham',        'با هم'],
['Go!',            'Boro',           'برو'],
['Child',          'Farzand',        'فرزند'],
[['By the way', 'Actually'],     'Raastee',        'راستی'],
['Complaint',      'Shekaaeeat',     'شکایت'],
['To Waste',       'Talaf Kardan',   'تلف کردن'],
['Roam Around',    'Gardesh Kardan', 'گردش کردن'],
['Possible',       'Momken',         'ممکن'],
['To Get Up',      'Paasho',         'پاشو'],
['Decision',       'Tasmeem',        'تصمیم'],
['To Decide',      'Tasmeem Gereftan', 'تصمیم گرفتن'],
['To Go',          'Beravam',        'بروم'],
['To Find',        'Paydaa Kardan',  'پیدا کردن'],
['(It / He / She) Wants', 'Meekhaahad', 'می خواهد'],
['News',           'Khabar',         'خبر'],
['(At the) Time',  'Mogh-e',         'موقع'],
['Someone',        'Kasee',          'کسی'],
['Memory',         'Yaad',           'یاد'],
['I Remembered',   'Yaadam Omad',    'یادم امد'],
['Permanent',      'Daaem',          'دائم'],
['Meaning',        ['Y\'anee', 'M\'anee'],        ['یعنی', 'معنی']],
['Piece',          'Tekeh',          'تکه'],
['Finished',       'Tamaam Shod',    'تمام شد'],
['North',          'Shomaal',        'شمال'],
['South',                       'Jonoob',                    'جنوب'],
['East',                        'Shargh',                    'شرق'],
['West',                        'Gharb',                     'غرب'],
['Butter',                      'Kareh',                     'کره'],
['Pair',                        'Joft',                      'جفت'],
['Bench',                       'Neemkat',                   'نیمکت'],
['Park',                        'Paark',                     'پارک'],
['Underwear',                   'Lebaas-e Ziir',             'لباس زیر'],
['Library',                     'Ketaabkhaane',              'کتابخانه'],
['Umbrella',                    'Chatr',                     'چتر'],
['Hundred',                     'Sa-d',                      'صد'],
['Jealous',                     'Hasood',                    'حسود'],
['Regret',                      'Hasrat',                    'حسرت'],
['One Time',                    'Yek Daf\'eh',               'یک دفعه'],
['Seed',                        'Daaneh',                    'دانه'],
['Edge',                        'Kenaareh',                  'کناره'],
['Taxi Driver',                 'Ranande Taksi',             'راننده تاکسی'],
['Unless',                      'Magar',                     'مگر'],
['Between',                     'Meeaan',                    'میان'],
['The Time For',                'Mogh-eh',                   'موقع'],
['However',                     'Albateh',                   'البته'],
['Simple',                      'Saadeh',                    'ساده'],
['Broken',                      'Shekasteh',                 'شکسته'],
['Outside',                     'Beeroon',                   'بیرون'],
['To Understand',               'Fahmidan',                  'فهمیدن'],
['Groan',                       'Naaleh',                    'ناله'],
['To curse someone',            'Nefreen',                   'نفرین'],
['(If you were) To Go',         'Beravee',                   'بروی '],
['Until you get old',           'Taa Peer Shavee',           'تا پیر شوی'],
['A Certain Way',               'Tor',                       'طور'],
['Net',                         'Toor',                      'تور'],
['Has your head been hit?',     'Magar be saret zadeh?',     'مگر بسرت زده؟'],
['Neighbour',                   'Hamsaayeh',                 'همسایه'],
['Tell Don\'t Tell (Chitchat)', 'Begoo Magooyee',            'بگو مگوی'],
['As Though',                   'Engaar',                    'انگار'],
['In the era (of)',             'Zamaaneh',                  'زمانه'],
['Blind',                       'Koor',                      'کور'],
['They Give',                   'Bedahand',                  'بدهند'],
['To Teach',                    'Yaad Daadan',               'یاد دادن'],
['Sometimes',                   'Gaahee',                    'گاهی'],
['(I) Get Going',               'Rah Beoftam',               'راه بیفتم'],
['Shelf',                       'Taaghcheh',                 'تاقچه'],
['Turned Out Well',             'Khoob Daraamadeh',          'خوب درآمده'],
['In a nonsensical fashion',    'Beekhodee',                 'بیخودی'],
['For Example',                 'Masalan',                   'مثلا'],
['Small unit of measurement',   'Vaajab',                    'واجب'],
['Wise',                        'Aalem',                     'عالم'],
['World',                       'Aalam',                     'عالم'],
['Philosopher',                 'Feelsoof',                  'فیلسوف'],
['Only',                        'Faghat',                    'فقط'],
['Fake',                        'Alakee',                    'الکی'],
['Wicked',                      'Badjens',                   'بدجنس'],
['In this way',                 'Eentoori',                  'اینطوری'],
['Tomato',                      'Gojeh Farangi',             'گوجه فرنگی'],
['Childhood',                   ['Koodaki', 'Bacchegi'],     ['کودکی', 'بچگی']],
['Noisy Chaos',                 ['Hayaahoo', 'Harj o Marj'], ['هیاهو', 'هرج  و مرج']],
['Coin',                        'Sek-keh',                   'سکه'],
['Banknote',                    'Eskenaas',                  'اسکناس'],
['Student',                     ['Daaneshjoo', 'Shaagerd'],  ['دانشجو', 'شاگرد']],
['Scissors',                    'Ghaychee',                  'قیچی'],
['Wolf',                        'Gorg',                      'گرگ'],
['Salary',                      'Hoghoogh',                  'حقوق'],
['Lizard',                      'Maarmoolak',                'مارمولک'],
['Bye (For Now)',               'Fehlan',                    ''],
['Hope to see you again',       'Be Omide Didar',            'به امیده دیدار'],
['Until Later',                 'Taa Ba-d',                  'تا بعد'],
['Until Tomorrow',              'Taa Fardaa',                'تا فردا'],
['Where are you from?',         'Taa Ahle Koja Hasti?',      'تو اهله کجا هستی؟'],
['I Live In London',            'Man Dar Landan Zendegi Mikonam', 'من در لندن زندگی می کنم'],
['Lawyer',                      'Vakeel',                    'وکیل'],
['Architect',                   'Me-maar',                   'معمار'],
['Author',                      'Neveesandeh',               'نویسنده'],
['Factory',                     'Karkhaane',                 'کارخانه'],
['What\'s your job?',            'Che kar-e hasti?',          'چه کار هستی'],
['Husband',                     'Shohar',                    'شوهر'],
['Tray',                        'Seenee',                    'سینی'],
['Valley',                      'Dareh',                     'دره'],
['Bee',                         'Zanboor',                   'زنبور'],
['Gift',                        ['Hedyeh', 'Kaado'],         ['هدیه', 'کادو']],
['Vinegar',                     'Serkeh',                    'سرکه'],
['Nonsense',                    'Mozakhraf',                 'مزخرف'],
[['Comb', 'Shoulder'],          'Shaaneh',                   'شانه'],
['Toothbrush',                  'Mesvaak',                   'مسواک'],
['Soap',                        'Saaboon',                   'صابون'],
['Mosque',                      'Masjed',                    'مسجد'],
['Headteacher',                 'Modeer',                    'مدیر'],
['Flag',                        'Parcham',                   'پرچم'],
['Suitable',                    'Monaaseb',                  'مناسب'],
['Bakery',                      'Naanvaaee',                 'نانوایی'],
['Retired',                     'Baazneshasteh',             'بازنشسته'],
['Newsagent',                   'Rooznaameh Forooshee',      'روزنامه فروشی'],
['To Sell',                     'Forookhtan',                'فروختن'],
['Page',                        'Safeh',                     'صفحه'],
['To Throw',                    'Andaakhtan',                'انداختن'],
[['Playground', 'Yard', 'Courtyard'], 'Hayaat',              'حیاط'],
['To Clean',                    'Tameez Kardan',             'تمیز کردن'],
['Board',                       'Takhteh',                   'تخته'],
['Blackboard',                  'Takhteh Siaa',              'تخته سیاه'],
['Nature',                      'Tabeeat',                   'طبیعت'],
['Chocolate',                   'Shokolaat',                 'شکلات'],
['Music',                       'Mooseghee',                 'موسیقی'],
['Exercise',                    'Varzesh',                   'ورزش'],
['Fiancé',                      'Naamzad',                   'نامزد'],
['Cheap',                       'Aarzaan',                   'ارزان'],
['Ant',                         'Moorcheh',                  'مورچه'],
['Frying Pan',                  'Maahee Taabeh',             'iماهی تابه'],
['Ladle',                       'Malaagheh',                 'ملاقه'],
['Sofa',                        'Mobl',                      'مبل'],
['Cabbage',                     'Kalam',                     'کلم'],
['Wow!',                        'Bah bah!',                  'به به'],
['Almond',                      'Baadaam',                   'بادام'],
['Real',                        'Vaagh-e-ee',                'واقعی'],
['Picture',                     'Tasveer',                   'تصویر'],
['Animal',                      'Heyvaan',                   'حیوان'],
['Without',                     'Beeaanke',                  'بی آنکه'],
['Insect',                      'Saas',                      'ساس'],
['Sam',                         'Poison',                    'سم'],
['Bride',                       'Aroos',                     'عروس'],
['Rooster',                     'Khoroos?',                  'خروس'],
[['(A) Groom', 'Son In Law?'],  'Daamaad',                   'داماد'],
['Price',                       'Gheymat',                   'قیمت'],
['Pencil Sharpener',            'Taraash',                   'تراش'],
['Marble (Ball)',               'Teeleh',                    'تیله'],
['(A) Swing',                   'Taab',                      'تاب'],
['(A) Whistle',                 'Soot',                      'سوت'],
['Sweat',                       'Aragh',                     'عرق'],
['Iraq',                        'Araagh',                    'عراق'],
['Strength',                    'Zoor',                      'زور'],
['Template of Strength',        'Zoorkhaane',                'زورخانه'],
['Upper Arm',                   'Baazoo',                    'بازو'],
['Needle',                      'Soozan',                    'سوزن'],
['To Sew',                      'Dooktan',                   'دوختن'],
['She Sews',                    'Midoozad',                  'می دوزد'],
['Skirt',                       'Daaman',                    'دامن'],
['Knee',                        'Zaanoo',                    'زانو'],
['Goose',                       'Ghaaz',                     'غاز'],
['Tool',                        'Abzaar',                    'ابزار'],
['Basement',                    'Ziirzameen',                'زیر زمین'],
['Underground',                 'Ziir Zameen',               'زیر  زمین'],
['(He) Makes',                  'Misaazad',                  'می سازد'],
['To Make',                     'Saakhtan',                  'ساختن'],
['Toy',                         'Asbaab Baazi',              'اسباب بازی'],
['Giraffe',                     'Zarraafe',                  'زرافه'],
['How\'s It Going',             'Chetour Peesh Mir-e',       'چطور پیش میره'],
['I\'m learning Farsi',         'Daaram Farsi Yaad Migiram', 'دارم فارسی یاد می گیرم'],
['Kitchen',                     'Aashpazkhaaneh',            'اشپزخانه'],
['Art',                         'Honar',                     'هنر'],
['Turtle',                      'Laakposht',                 'لاک پشت'],
['To Fly',                      'Parvaaz Kardan',            'پرواز کردن'],
['Recipe',                      'Dastoorol Amal',            'دستور العمل'],
['To Speak',                    'Sohbat',                    'صحبت'],
['Please speak more slowly',    'Lotfan Yavaashtar Sohbat Konid', 'لطفآ یواش تر صحبت کنید'],
['What is it in Farsi?',        'Beh Farsi Chi Mishe?',      'به فارسی چی میشه'],
['Camera',                      'Doorbeen',                  'دوربین'],
['This Alone',                  'Tanhaa Hameen',             'تنها همین'],
['I am killing',                'Mikosham',                  'می کشم'],
['To Kill',                     'Koshtan',                   'کشتن'],
['(A) Type',                    'Joor',                      'جور'],
['To Digest',                   'Hazm Kardan',               'هضم کردن'],
['To Design',                   'Tarh Kardan',               'طرح  کردن '],
['(A) Design',                  'Tarraahee',                 'طراحی'],
['(A) Translation',             'Tarjomeh',                  'ترجمه'],
['Bank Account',                'Hesaabe Baanki',            'حساب بانکی'],
['Order (Given)',               'Dastoor',                   'دستور'],
['Secret',                      'Raaz',                      'راز'],
['Are You Ready?',              'Haazeri',                   'حاضری'],
['Snake',                       'Maar',                      'مار'],
['But',                         ['Vali', 'Balkeh'],          ['ولی', 'بلکه']],
['I Could',                     'Tavaanestam',               'توانستم'],
['I Can',                       'Meetavaanam',               'می توانم'],
['Single',                      'Tek',                       'تک'],
['(Current) Status',            'Ahvaal',                    'احوال'],
['Wing',                        'Baal',                      'بال'],
['Africa',                      'Aafrighaa',                 'آفریقا'],
['Nut (Bolt)',                  'Mohreh',                    'مهره'],
['Flame',                       'Shoh-leh',                   'شعله'],
['Earthquake',                  'Zelzeleh',                  'زلزله'],
['Discount',                    'Takhfeef',                  'تخفیف'],
['Sword',                       'Shamsheer',                 'شمشیر'],
['Gun',                         'Tofang',                    'تفنگ'],
['Gather Round',                'Jamh Sheed',                'جمع شید'],
['Pain',                        'Dard',                      'درد'],
['That Hit The Spot',           'Chasbeed',                  'چسبید'],
['Backpack',                    'Kooleh Poshtee',            'کوله پشتی'],
['Beach',                       'Saahel',                    'ساحل'],
['Seaside',                     'Lab-e Dareaa',              'لب دریا'],
['Government',                  ['Hokoomat', 'Daolat'],      ['حکومت', 'دولت']],
['Stingy',                      'Khasees',                   'خسیس'],
['Demon',                       'Deev',                      'دیو'],
['Metal',                       'Felez',                     'فلز'],
['Creature',                    'Jaanevar',                  'جانور'],
['Rock',                        'Sakhreh',                   'صخره'],
['Welcome',                     'Khosh Aamadeed',            'خوش آمدید'],
['Person',                      'Aadam',                     'آدم'],
['Road',                        ['Jaaddeh', 'Kheeaabaan'],   ['جاده', 'خیابان']],
['(The) Moment',                'Lahzeh',                    'لحظه'],
['Breath',                      'Nafas',                     'نفس'],
['Dove',                        'Kabootar',                  'کبوتر'],
['Life (span)',                 'Omr',                       'عمر'],
['Dancing',                     'Raghs',                     'رقص'],
['Sparkle',                     'Talaalo',                   'تلالو'],
['Don\'t Worry',                'Na-tars',                   'نترس'],
['Suffering',                   'Ranj',                      'رنج'],
['Trumpet',                     'Sheypoor',                  'شیپور'],
['Humiliation',                 'Tah-gheer',                 'تحقیر'],
['Food',                        ['Ghazaa', 'Khooraakee'],    ['غذا', 'خوراکی']],
['Prostitution',                'Fahshaa',                   'فحشا'],
['Pipe',                        'Looleh',                    'لوله'],
['Pocket',                      'Jeeb',                      'جیب'],
['To Wink',                     'Cheshmak Zadan',            'چشمک زدن'],
['Forever',                     'Taa Abad',                  'تا ابد'],
['Alley',                       'Koocheh',                   'کوچه'],
['Swearword',                   'Fohsh',                     'فحش'],
['Leaf',                        'Barg',                      'برگ'],
['Soul',                        'Rooh',                      'روح'],
['Sun',                         ['Aaftaab', 'Khoorsheed'],   ['افتاب', 'خورشید']],
['Breeze',                      'Naseem',                    'نسیم'],
['Rubbish (Trash)',             'Aashghaal',                 'آشغال'],
['Joke',                        'Shookhee',                  'شوخی'],
['(A) Savage',                  'Vahshee',                   'وحشی'],
['Half',                        ['Neem', 'Nesf'],            ['نیم', 'نصف']],
['(A) Drop',                    'Ghatreh',                   'قطره'],
['Peasant',                     'Rayeat',                    'رعیت'],
['Orphan',                      'Yateemee',                  'یتیمی'],
['Tears',                       'Ashk',                      'اشک']
['Poverty',                     'Faghr',                     'فقر'],
['(Dog) Bark',                  'Paars',                     'پارس'],
['Fatty',                       'Charb',                     'چرب'],
['Criterion',                   'Melaak',                    'ملاک'],
['Sending Someone To Coventry', 'Ghahr',                     'قهر'],
['Fig',                         'Anjeer',                    'انجیر'],
['Destruction',                 'Veeraanee',                 'ويرانی'],
['Light (Sun)',                 'Noor',                      'نور'],
['Death',                       'Marg',                      'مرگ'],
['Companion',                   'Hamsafar',                  'همسفر'],
['Listen!',                     'Beshno',                    'بشنو'],
['Again',                       'Dobare',                    'دوباره'],
['Wave (Sea)',                  'Moj',                       'موج'],
['Pregnant',                    'Hameleh',                   'حامله'],
['To Crush',                    'Leh Kardan',                'له کردن'],
['Naughtiness',                 'Sheytooni',                 'شیطونی'],
['Eyelid',                      'Pelk',                      'پلک'],
['A Yawn', 	                    'Khameeaazeh',               'خمیازه'],
['A Fly', 	                    'Magasee',                   'مگسی'],
['You Have The Right', 	        'Hagh Daaree',               'حق داری'],
['Wage', 	                      'Mozd',                      'مزد'],
['Trouble', 	                  'Dardesar',                  'دردسر'],
['To Help', 	                  'Komak Kardan',              'کمک کردن'],
['Goat', 	                      'Boz',                       'بز'],
['Boat',                        'Ghaayegh',                  'قایق'],
['Grape',                       'Aangoor',                   'انگور'],
['Peach',                       'Holoo',                     'هلو'],
['Yellow',                      'Zard',                      'زرد'],
['Fence',                       'Nardeh',                    'نرده'],
['Ladder',                      'Nardebaan',                 'نردبان'],
['Ice',                         'Yakh',                      'یخ'],
['Heaven',                      'Behesht',                   'بهشت'],
['Deer',                        'Aahoo',                     'آهو'],
['Shepherd',                    'Choopaan', 'چوپان'],
['Mushroom',                    'Ghaarch', 'قارچ'],
['Fountain',                    'Cheshmeh', 'چشمه'],
['Network',                     'Shabkeh', 'شبکه'],
['Social',                      'Ejtamaayee', 'اجتماعی'],
['Warning',                     'Ekhtar', 'اخطار'],
['Angry',                       'Asabaanee', 'عصبانی'],
['Even',                        'Hat\'taa', 'حتی'],
['Soon',                        'Behzoodee', 'به زودی'],
['The Tip',                     'Nok', 'نک'],
['Direction',                   'Jahat', 'جهت'],
['To Bend',                     'Kham Shodan', 'خم شدن'],
['To Wear',                     'Poosheedan', 'پوشیدن'],
['Electricity',                 'Bargh', 'برق'],
['Scary', 'Tarsnaak', 'ترسناک'],
['Thunder', 'Rad', 'رعد'],
['Terrified', 'Zahreh Tark', 'زهره ترک'],
['To Burst', 'Tarkeed', 'ترکید'],
['Severe', 'Shadeed', 'شدید'],
['Horrible', 'Vahshatnaak', 'وحشتناک'],
['Layer', 'Laayeh', 'لایه'],
['To Exit', 'Khaarej Shodan', 'خارج شدن'],
['Dark', 'Taareek', 'تاریک'],
['Bizarre', 'Ghareeb', 'غریب'],
['(A) Show', 'Nemaayesh', 'نمایش'],
['Carrot', 'Haveej', 'هویج'],
['Shirt', 'Peeraahan', 'پیراهن'],
['Overcoat', 'Paalto', 'پالتو'],
['Purple', 'Banafsh', 'بنفش'],
['Towel', 'Holeh', 'حوله'],
['Bridge', 'Pol', 'پل'],
['Pharmacy', 'Daarookhaane', 'داروخانه'],
[['Drug', 'Medicine'], 'Daaroo', 'دارو'],
['Shopping', 'Khareed', 'خرید'],
['Pâtisserie', 'Ghanaadee', 'قنادی'],
['Paper', 'Kaaghaz', 'کاغذ'],
['Bowl', 'Kaaseh', 'کاسه'],
['Credit Card', 'Kaart-e Etebaaree', 'کارت اعتباری'],
['Bedsheet', 'Malaafeh', 'ملافه'],
['Fast', 'Sareeh', 'سریع'],
['Slow', ['Kond', 'Yavaash', 'Aahesteh'], ['کند', 'یواش', 'اهسته']],
['Actor', 'Baazeegar', 'بازیگر'],
['Director', 'Kaargardaan', 'کارگردان'],
['Song', 'Aavaaz', 'آواز'],
['Festival', 'Jashnvaareh', 'جشنواره'],
['Interview', 'Mosaahebeh', 'مصاحبه'],
['Court', 'Daadgaah', 'دادگاه'],
['A Group', 'Gorooh', 'گروه'],
['Chewing Gum', 'Aadaams', 'آدامس'],
['Strawberry', 'Toot Farangi', 'توت فرنگی'],
['Mulberry', 'Toot', 'توت'],
['Date (Fruit)', 'Khormaa', 'خرما'],
['Plum', 'Aaloo', 'آلو'],
['Outcome', 'Payaamad', 'پیامد'],
['Queen', 'Malkeh', 'ملکه'],
['Independence', 'Aastaghaalal', 'استقلال'],
['What\'s On Your Mind?', 'Dar Che Fekr Hastid', 'در چه فکر هستید'],
['To Surprise', 'Mota\'a\'jeb Kardan', 'متعجب کردن'],
['Planet', 'Sayaareh', 'سیاره'],
['Telescope', 'Doorbeen Nejoomee', 'دوربین نجومی'],
['Swimming Pool', 'Estakhr', 'استخر'],
['Church', 'Keleesaa', 'کلیسا'],
['Synagogue', 'Keneeseh', 'کنیسه'],
['Walnut', 'Gerdoo', 'گردو'],
['Jam', 'Mora\'baa', 'مربا'],
['Pepper', 'Felfel', 'فلفل'],
['Dessert', 'Deser', 'دسر'],
['Mate', 'Rafeegh', 'رفیق'],
['Darling', 'Naazaneem', 'نازنینم'],
['Brains And Wit', 'Aghl o Hoosh', 'عقل و هوش'],
['I had a great time', 'Kheili khosh gozaasht', 'خیلی خوش گذاشت'],
['I need to get going', 'Baayad yavaash yavaash beram', 'باید یواش یواش برم'],
['String', 'Nakh', 'نخ'],
['Crab', 'Kharchang', 'خرچنگ'],
['Worm', 'Kerm', 'کرم'],
['Blossom', 'Shokoofeh', 'شکوفه'],
['Nightingale', 'Bolbol', 'بلبل'],
['Butterfly', 'Parvaaneh', 'پروانه'],
['Restlessness', 'Bigharaaree', 'بی قراری'],
['Tulip', 'Laaleh', 'لاله'],
['Crack', 'Shekaaf', 'شکاف'],
['Same Gender', 'Hamjens', 'همجنس'],
['Waterfall', 'Aabshaar', 'آبشار'],
['Hurry', 'Ajaleh', 'عجله'],
['Hunter', 'Shekaarchee', 'شکارچی'],
['A Stranger', 'Ghareebeh', 'غریبه'],
['River', 'Roodkhaaneh', 'رودخانه'],
['Temptation', 'Vasvaseh', 'وسوسه'],
['Pilot', 'Khalabaan', 'خلبان'],
['Airport', 'Foroodgaah', 'فرودگاه'],
['Enough', 'Kaafee', 'کافی'],
['Never', 'Hargez', 'هرگز'],
['Hunting', 'Shekaar', 'شکار'],
['Sugar', 'Shekar', 'شکر'],
['Robin', 'Seenehsorkh', 'سینه سرخ'],
['Delicate', 'Lateef', 'لطیف'],
['Let Me Be', 'Raahatam Bezaar', 'راحتم بذار'],
['Dragonfly', 'Sanjaaghak', 'سنجاقک'],
['Ordinary', 'Ma\'mool', 'معمولی'],
['Pond', 'Berkeh', 'برکه'],
['For this reason', 'Be hameen daleel', 'به همین دلیل'],
['The Center', 'Markaz', 'مرکز'],
['Unhappy', 'Naaraahat', 'ناراحت'],
['To Love', 'Aashegh', 'عاشق'],
['Closed', 'Tateel', 'تعطیل'],
['Match (Sport)', 'Mosaabegheh', 'مسابقه'],
['Opponent', 'Hareef', 'حریف'],
['Referee', 'Daavar', 'داور'],
['Satisfied', 'Raazee', 'راضی'],
['Result', 'Nateejeh', 'نتیجه'],
['Victory', 'Peeroozee', 'پیروزی'],
['Equal', 'Mosaavee', 'مُساوی'],
['Winner', 'Barandeh', 'برنده'],
['Lucky', 'Khoshshaans', 'خوش شانس'],
['How Much', 'Cheghadr', 'چقدر'],
['To Practice', 'Tamreen Kardan', 'تمرین کردن'],
['Chemical', 'Sheemeeaaee', 'شیمیایی'],
['I Heard', 'Sheneedam', 'شنیدم'],
['Bomb', 'Bom-b', 'بمب'],
['Explosion', 'Aanfejaar', 'انفجار'],
['Crowded', 'Sholoogh', 'شلوغ'],
['Sneakily', 'Yavaashakee', 'یواشکی'],
['Mistake', 'Eshtebaah', 'اشتباه'],
['Vomit', 'Estefraagh', 'استفراغ'],
['(A) Second', 'Saanyeh', 'ثانیه'],
['Cool', 'Khonak', 'خنک'],
['Garden', 'Baagh', 'باغ'],
['Blonde', 'Boor', 'بور'],
['Red', ['Ghermez', 'Sorkh'], ['قرمز', 'سرخ']],
['Quick', 'Ferz', 'فرز'],
['Humid', 'Martoob', 'مرطوب'],
['It\'s Raining', 'Daare Baaraan Miaad', 'داره باران میاد'],
['It\'s Going To Rain', 'Baaraan Miaad', 'باران میاد'],
['Dry', 'Khoshk', 'خشک'],
['Friendship', 'Doostee', 'دوستی'],
['Give Me A Kiss', 'Boos Bedeh', 'بوس بده'],
['Single (Relationship)', 'Mojarad', 'مجرد'],
['Beginning', 'Aaghaaz', 'آغاز'],
['Elf', 'Vooroojak', 'وروجک'],
['Tiny', 'Fesghelee', 'فسقلی'],
['Map', 'Naghsheh', 'نقشه'],
['Too', 'Neez', 'نیز'],
['Individuals', 'Afraad', 'افراد'],
['Scenery', 'Manzareh', 'منظره'],
['Steering Wheel', 'Farmaan', 'فرمان'],
['Season', 'Fasl', 'فصل'],
['Cape', 'Shenel', 'شنل'],
['Junk', 'Bonjol', 'بنجل'],
['Cucumber', 'Kheeaar', 'خیار'],
['Neighbourhood', 'Mahaleh', 'محله'],
['How old are you?', 'Chand saal daarid?', 'چند سال دارید؟'],
['Weekend', 'Aakhar-e Hafteh', 'آخر هفته'],
['Around', 'Atraaf', 'اطراف'],
['Resident', 'Saaken', 'ساکن'],
['Owner', 'Saaheb', 'صاحب'],
['Until Now', 'Taa Be Haal', 'تا به حال'],
['Buggy', 'Kaaleskeh', 'کالسکه'],
['Nourishment', 'Aazogheh', 'آذوقه'],
['Free', 'Raayegaan', 'رایگان'],
['Fall of (Rain/Snow)', 'Baaresh', 'بارش'],
['Parrot', 'Tootee', 'طوطی'],
['Primrose', 'Paamchaal', 'پامچال'],
['Daffodil', 'Narges', 'نرگس'],
['Arranged', 'Cheedeh', 'چیده'],
['Newborn', 'No-zaad', 'نوزاد'],
['Musical Instrument', 'Saaz', 'ساز'],
['Iranian Fiddle', 'Kamaancheh', 'کمانچه'],
['Law', 'Ghaanoon', 'قانون'],
['Cello', 'Veeolinsel', 'ویولنسل'],
['Violin', 'Veeolin', 'ویولن'],
['Clarinet', 'Klaareenet', 'کلارینت'],
['Lemon', 'Leemoo', 'لیمو'],
['Pear', 'Golaabee', 'گلابی'],
['Zero', 'Sefr', 'صفر'],
['2nd', 'Do-vom', 'دوم'],
['3rd', 'Se-vom', 'سوم'],
['4th', 'Chahaar-om', 'چهارم'],
['5th', 'Panj-om', 'پنجم'],
['6th', 'Shesh-om', 'ششم'],
['7th', 'Haft-om', 'هفتم'],
['8th', 'Hasht-om', 'هشتم'],
['9th', 'Noh-om', 'نهم'],
['10th', 'Dah-om', 'دهم'],
['Not Working', 'Kharaab', 'خراب'],
['Front', 'Jelo', 'جلو'],
['Next (To)', 'Kenaar', 'کنار'],
['Interior', 'Daakheleh', 'داخله'],
['Once Per Day', 'Har Rooz Yek Baar', 'هر روز یک بار'],
['Opposite (To)', 'Rooberoo', 'روبرو'],
['Bag (Sack)', 'Keeseh', 'کیسه'],
['Wheat', 'Gandom', 'گندم'],
['Barley', 'Jo', 'جو'],
['Lentil', 'Adas', 'عدس'],
['Bean', 'Loobeeaa', 'لوبیا'],
['Chickpea', 'Nokhod', 'نخود'],
['Sunset', 'Ghoroob', 'غروب'],
['To See Someone Off', 'Badregheh Kardan', 'بدرقه کردن'],
['Storm', 'Toofaan', 'طوفان'],
['Cold (Weather)', 'Sarmaa', 'سرما'],
['Illness', 'Beemaaree', 'بیماری'],
['(A) Patient', 'Beemaar', 'بیمار'],
['Resident', 'Saaken', 'ساکن'],
['Drawing', 'Naghaashee', 'نقاشی'],
['Dawn', 'Sepeedeh', 'سپیده'],
['Humanity', 'Ensaaniat', 'انسانیت'],
['Shame', 'Sharm', 'شرم'],
['Person', 'Nafar', 'نفر'],
['Other Than', 'Gheer Az', 'غیر از'],
['Person', 'Nafar', 'نفر'],
['Adventure', 'Maajeraa', 'ماجرا'],
['Topic', 'Mozooh', 'موضوع'],
['Clock Hand', 'Aghrabeh', 'عقربه'],
['Hanging', 'Aaveezaan', 'آویزان'],
['Smooth', 'Saaf', 'صاف'],
['Ready', 'Aamaadeh', 'آماده'],
['Distance', 'Faaseleh', 'فاصله'],
['To Take (Future He/She/It)', 'Bebarad', 'ببرد'],
['Was Supposed To Happen', 'Gharaar Bood', 'قرار بود'],
['To Move (In-Motion)', 'Harkat Kardan', 'حرکت کردن'],
['Quiet',          ['Saaket', 'Aaraam'],         ['ساکت', 'آرام']],
['Noon', 'Zohr', 'ظهر'],
['Turned Off (Light)', 'Khaamoosh', 'خاموش'],
['(A) Light', 'Cheraagh', 'چراغ'],
['Clock', 'Sa\'at Deevaaree', 'ساعت دیواری'],
['To Try', 'Saey', 'سعی کردن'],
['Successful', 'Movafagh', 'موفق'],
['Staring', 'Kheereh', 'خیره'],
['Clever', ['Baahoosh', 'Zerang'], ['باهوش', 'زرنگ']],
['Nose', ['Beenee', 'Damaagh'], ['بینی', 'دماغ']],
['Sharp', 'Teez', 'تیز'],
['Same', 'Ayn', 'عین'],
['Owl', 'Joghd', 'جغد'],
['Skewer', 'Seekh', 'سیخ'],
['Pothole', 'Cheleh Chooleh', 'چاله چوله'],
['Wrinkle', 'Charook', 'چروک'],
['Crease', 'Cheen', 'چین'],
['Groove', 'Sheeaar', 'شیار'],
['Deep', 'Ameegh', 'عمیق'],
['Bone', 'Ostokhaan', 'استخوان'],
['Unaware', 'Ghaafel', 'غافل'],
['Taste', 'Mazeh', 'مزه'],
['Hole', 'Sooraakh', 'سوراخ'],
['Answer', ['Paasokh', 'Javaab'], ['پاسخ', 'جواب']],
['Head', ['Sar', 'Kaleh'], ['سر', 'کله']],
['Bald Head', 'Kaleh Taas', 'کله طاس'],
['Dice', 'Taas', 'تاس'],
['Various', ['Goonaagoon', 'Jooraajoor'], ['گوناگون', 'جوراجور']],
['Device', 'Vaseeleh', 'وسیله'],
['Professor', 'Aastaad', 'استاد'],
['Caricature', 'Kaareekaatoor', 'کاریکاتور'],
['To Study', 'Dars Khaandan', 'درس خواندن'],
['Lesson', 'Dars', 'درس'],
['I am studying', 'Man dars mikhaanam', 'من درس میخوانم'],
['Recently', 'Taazehgee', 'تازهگی'],
['Office', ['Edaareh', 'Daftar'], ['اداره', 'دفتر']],
['Pencil', 'Madaad', 'مداد'],
['I Hope', 'Omeedvaaram', 'امیدوارم'],
['To Gaze', 'Zol Zadan', 'زل زدن'],
['Hole', 'Sooraakh', 'سوراخ'],
['Cake', 'Keyk', 'کیک'],
['(Ice Cream) Cone', 'Gheef', 'قیف'],
['Pickled Cucumbers', 'Kheeaar Shoor', 'خیار شور'],
['(A) Slice', 'Ghaach', 'قاچ'],
['Salami', 'Salaamee', 'سلامی'],
['Boiled Sweets', 'Aab Nabaat', 'آب نبات'],
['Cherry', 'Geelaas', 'گیلاس'],
['Pie', 'Paaee', 'پای'],
['Sausage', 'Sosees', 'سوسیس'],
['Silk', 'Abreesham', 'ابریشم'],
['Chubby (Cute)', 'Topl O Mopl', 'تپل و مپل'],
['Cocoon', 'Peeleh', 'پیله'],
['Remained', ['Moond', 'Maandeh Bood'], ['موند', 'مانده بود']],
['Chewed', 'Javeed', 'جوید'],
['Feather', 'Par', 'پر'],
['University', 'Daaneshgaah', 'دانشگاه'],
['Duck', 'Ordak', 'اردک'],
['Frog', 'Ghoorbaaregh', 'قورباغه'],
['Horizontal', 'Ofoghee', 'افقی'],
['Vertical', 'Omoodee', 'عمودی'],
['Hippopotamus', 'Asb Aabee', 'اسب آبی'],
['Shark', 'Kooseh', 'کوسه'],
['Dental Floss', 'Nakh Dandaan', 'نخ دندان'],
['It\'s Very Enjoyable', 'Kheili Kayf Daareh', 'خیلی کیف داره'],
['In Motion', 'Dar Harket', 'در حرکت'],
['Remained', 'Maandeh', 'مانده'],
['Stayed In Place', 'Jaa Maandeh', 'جا مانده'],
['Hidden From View', 'Az Nezar Penhaan', 'از نظر پنهان'],
['Hidden', 'Penhaan', 'پنهان'],
['Inside', 'Daakhel', 'داخل'],
['To Jump', 'Pareedan Kardan', 'پریدن کردن'],
['To Pass (By/Through)', 'Oboor Kardan', 'عبور کردن'],
['Clown', 'Dalghak', 'دلقک'],
['Shrimp', 'Meygoo', 'میگو'],
['Seashell', 'Sadaf', 'صدف'],
['Jellyfish', 'Chatr-e Dareeaaee', 'چتر دریایی'],
['Squid', 'Maaheeye Morakab', 'ماهی مرکب'],
['Ocean', 'Ogheeaanoos', 'اقیانوس'],
['Octopus', 'Hashtpaa', 'هشتپا'],
['Whale', 'Nahang', 'نهنگ'],
['Bedroom', 'Otaagh Khaab', 'اطاق خواب'],
['The Remaining', 'Bagheeyeh', 'بقیه'],
['To Move', 'Takoon Khordan', 'تکون خوردن'],
['Some (Measurable)', 'Meghdaari', 'مقداری'],
['Some (A Few)', 'Ba\'zee', 'بعضی'],
['I Can', 'Man Meetoonam', 'من میتونم'],
['I Hear', 'Man Meeshnavam', 'من می شنوم'],
['I Am Smelling', 'Man Boo Mikonam', 'من بو می کنم'],
['I Am Tasting', 'Man Meechesham', 'من میچشم'],
['I Am Touching', 'Man Lams Mikonam', 'من لمس میکنم'],
['Balloon', 'Baadkonak', 'بادکنک'],
['Painting', 'Taabloo', 'تابلو'],
['Glove', 'Dastkesh', 'دستکش'],
['Brush', 'Boros', 'برس'],
['Bellybutton', 'Naaf', 'ناف'],
['Curious', 'Konjkaav', 'کنجکاو'],
['Headache', 'Sardard', 'سردرد'],
['Pile', 'Toodeh', 'توده'],
['Faeces', 'Madfooh', 'مدفوع'],
['Close It (Command)', 'Beband', 'ببند'],
['Throne', 'Arsh', 'عرش'],
['Crime', 'Jorm', 'جرم'],
['Officer', 'Mamoor', 'مامور'],
['Fireman', 'Mamoore Aatish Neshaanee', 'مامور آتش نشانی'],
['Station', 'Aeestgaah', 'ایستگاه'],
['Farm', 'Mazr-a-eh', 'مزرعه'],
['Farmer', 'Keshaavarz', 'کشاورز'],
['Tractor', 'Teraaktoor', 'تراکتور'],
['Museum', 'Moozeh', 'موزه'],
['Scientist', 'Daaneshmand', 'دانشمند'],
['Chef', 'Aashpaz', 'آشپز'],
['Doorman', 'Darbaan', 'دربان'],
['Astronaut', 'Fazaanavard', 'فضانورد'],
['Plumber', 'Loolehkesh', 'لوله کش'],
['Baker', 'Noonvaa', 'نونوا'],
['Thief', 'Dozd', 'دزد'],
['Pirate', 'Dozd-e Dareeaaee', 'دزد دریایی'],
['Acrobat', 'Aakroobaat', 'آکروبات'],
['Employee', 'Kaarmand-e Sherkat', 'کارمند شرکت'],
['Respectable', 'Mohtaram', 'محترم'],
['Passport', 'Gozarnaameh', 'گذرنامه'],
['Boss', 'Rayees', 'رئیس'],
['I Have An Accent', 'Man Lahjeh Daaram', 'من لهجه دارم'],
['I Am Joking', 'Shookhi Mikonam', 'شوخی میکنم'],
['Food Poisoning', 'Masmoomeeat Ghazaaee', 'مسمومیت غذایی'],
['President', 'Rayees-e Jomhoor', 'رئیس جمهور'],
['Hungary', 'Majaarestaan', 'مجارستان'],
['Bath', 'Vaan', 'وان'],
['Hobby', 'Sargarmee', 'سرگرمی'],
['Appetite', 'Eshtehaa', 'اشتها'],
['(A) Stew', 'Khoresht', 'خورشت'],
['I\'m Sure', 'Motmaennam', 'مطمئنم'],
['(Good) Sense', 'Sho\'oor', 'شعور'],
['Calmly', 'Baa Khoonsardee', 'با خونسردی'],
['Exaggeration', 'Eghraagh', 'اغراق'],
['(A) Power', 'Neeroo', 'نیرو'],
['Earmuffs', 'Roogoosheehaa', 'روگوشی ها'],
['Penetrating Look', 'Negaahe Naafez', 'نگاه نافذ'],
['Belief', 'Baavar', 'باور'],
['I Can\'t Believe It', 'Baavaram Nemishe', 'باورم نمیشه'],
['Shaky', 'Larzaan', 'لرزان'],
['Handkerchief', 'Dastmaal', 'دستمال'],
['To Wipe', 'Paak Kardan', 'پاک کردن'],
['Digit', 'Adad', 'عدد'],
['Opinion', 'Agheedeh', 'عقیده'],
['Brawl', 'Janjaal', 'جنجال'],
['Wait!', 'Sabr Kon', 'صبر کن!'],
['Guest', 'Mehmaan', 'مهمان'],
['You Look Pale', 'Ranget Pareedeh', 'رنگت پریده'],
['Able', 'Ghaabel', 'قابل'],
['Trust', 'Etemaad', 'اعتماد'],
['Stature', 'Ghaamat', 'قامت'],
['Physique', 'Haykal', 'هیکل'],
['Huge / Great', 'Azeem', 'عظیم'],
['(A) Doubt', 'Shak', 'شک'],
['Motorbike', 'Motoorseeklet', 'موتورسیکلت'],
['Reluctantly', 'Baa Ekraah', 'با اکراه'],
['Complete (Full)', 'Kaamel', 'کامل'],
['Greedy', 'Harees', 'حریص'],
['History', 'Taareekh', 'تاریخ'],
['Community', 'Anjoman', 'انجمن'],
['Bottle', 'Botree', 'بطری'],
['Pen', 'Ghalam', 'قلم'],
['Signature', 'Emzaa', 'امضا'],
['Religion', 'Deen', 'دین'],
['False', 'Ghalat', 'غلط'],
['Lie', 'Doroogh', 'دروغ'],
['Useful', 'Mofeed', 'مفید'],
['Harmful', 'Mozer', 'مضر'],
['Doctor', 'Pezeshk', 'پزشک'],
['Medium (Size)', 'Motevaset', 'متوسط'],
['Oven', 'Ojaagh', 'اجاق'],
['Constipation', 'Yoboosat', 'یبوست'],
['Diarrhoea', 'Es-haal', 'اسهال'],
['Fridge', 'Yakhchaal', 'یخچال'],
['(A) Giant', 'Ghool', 'غول'],
['Caution', 'Ehteeaat', 'احتیاط'],
['Excellency (Sir)', 'Jenaab', 'جناب'],
['Bless You!', 'Aafeeat Baasheh', 'عافیت باشه'],
['Before', ['Peesh Az', 'Ghabl'], ['پیش از', 'قبل']],
['Effect', 'Asar', 'اثر'],
['(A) Wound', 'Zakhm', 'زخم'],
['Similar', 'Shabeeh', 'شبیه'],
['Rough (Coarse)', 'Zebr', 'زبر'],
['Yap / Howl (Dog)', 'Zoozeh', 'زوزه'],
['Shhh!', 'Hees!', 'هیس!'],
['Spot / Mole', 'Khaal', 'خال'],
['Hapless', 'Beechaareh', 'بیچاره'],
['Protection', 'Hafez', 'حفظ'],
['Building', 'Saakhtemaan', 'ساختمان'],
['(A) Time', 'Gaah', 'گاه'],
['Finally', ['Belakhareh', 'Saranjaam'], ['بالاخره', 'سرانجام']],
['Bundle', 'Boghcheh', 'بقچه'],
['That\'s That', 'Eenam Az Een', 'اینم از این'],
['Celebration', 'Jashn', 'جشن'],
['Sleeve', 'Aasteen', 'آستین'],
['Tear (Drop)', 'Ashk', 'اشک'],
['Useful', 'Mofeed', 'مفید'],
['Mint', 'Na\'naah', 'نعناع'],
['Traveller', 'Mosaafer', 'مسافر'],
['Travel', 'Mosaafer', 'مسافرت'],
['Noble / Decent', 'Najeeb', 'نجیب'],
['(One\'s) Honor', 'Sheraafat', 'شرافت'],
['Madam', 'Sarkaar-e Khanoom', 'سرکار خانم'],
['Politics', 'Seeaasat Baazee', 'سیاست بازی'],
['Politician', 'Seeaasatmadaar', 'سیاستمدار'],
['Hypocrisy', 'Reeaa', 'ریا'],
['Rust', 'Zang', 'زنگ'],
['Ruler (Drawing)', 'Khatkesh', 'خط کش'],
['Ink', 'Johar', 'جوهر'],
['Ironing', 'Aatoo Keshee', 'اتو کشی'],
['Turnip', 'Shalgham', 'شلغم'],
['Schedule', 'Barnaameh', 'برنامه'],
['Body', 'Badan', 'بدن'],
['Throat', 'Goloo', 'گلو'],
['Stomach', 'Shekam', 'شکم'],
['Lipstick', 'Maateek', 'ماتیک'],
['Bucket', 'Satl', 'سطل'],
['Shovel', 'Beelcheh', 'بیلچه'],
['(A) Sail', 'Baadbaan', 'بادبان'],
['Harmless', 'Beeaazaar', 'بیازار'],
['Castle', 'Ghal\'eh', 'قلعه'],
['Blanket', 'Patoo', 'پتو'],
['Disinfectant', 'Zede Ofoonee', 'ضد عفونی'],
['Honesty', 'Sedaaghat', 'صداقت'],
['Biting', 'Gaaz Gereftan', 'گاز گرفتن'],
['Infection', 'Ofoonat', 'عفونت'],
['Annoying (Disturbance)', 'Mozaahem', 'مزاحم'],
['Infection', 'Hasaaseet', 'حساسیت'],
['I Am Giving', 'Meedaham', 'می دهم'],
['I Gave', 'Daadam', 'دادم'],
['I Am Taking', 'Meegeeram', 'می گیرم'],
['I Took', 'Gereftam', 'گرفتم'],
['I Am Drinking', 'Meenoosham', 'می نوشم'],
['I Drank', 'Noosheedam', 'نوشیدم'],
['I Am Hearing', 'Meeshnavam', 'می شنوم'],
['I Heard', 'Sheneedam', 'شنیدم'],
['I Am Running', 'Meedavam', 'می دوم'],
['I Ran', 'Daveedam', 'دویدم'],
['I Am Wearing', 'Meepoosham', 'می پوشم'],
['I Wore', 'Poosheedam', 'پوشیدم'],
['I Am Buying', 'Meekharam', 'می خرم'],
['I Bought', 'Khareedam', 'خریدم'],
['I Am Sitting', 'Meenesheenam', 'می نشینم'],
['I Sat', 'Neshastam', 'نشستم'],
['(A) Nap', 'Chort', 'چرت'],
['I Am Napping', 'Chort Meezanam', 'چرت میزنم'],
['I Napped', 'Chort Zadam', 'چرت زدم'],
['Tasteless / Boring', 'Beemazeh', 'بیمزه'],
['Ring (Shape)', 'Halgheh', 'حلقه'],
['A Wish / Dream', 'Aarzoo', 'آرزو'],
['Glass (Material)', 'Sheesheh', 'شیشه'],
['Islamic Republic', 'Jomhooree-ye Eslaamee', 'جمهوری اسلامی'],
['Broom', 'Jaaroo', 'جارو'],
['Tail', 'Dom', 'دم'],
['Naughty', 'Balaa', 'بلا'],
['Eloquent', 'Khosh Zabaan', 'خوش زبان'],
['Fingernail', 'Naakhoon', 'ناخن'],
['Immediate', 'Fooree', 'فوری'],
['Ass (Donkey)', 'Alaagh', 'الاغ'],
['Frown', 'Akhm', 'اخم'],
['Moody', 'Akhmoo', 'اخمو'],
['Beggar', 'Gedaa', 'گدا'],
['Waiting', 'Montazer', 'منتظر'],
['(A) Label', 'Eteeket', 'اتیکت'],
['Posse', 'Ekeep', 'اکیپ'],
['(Too) Salty', 'Shoor', 'شور'],
['Compulsory', 'Ejbaar', 'اجبار'],
['Sand', 'Maaseh', 'ماسه'],
['Faith', 'Eemaan', 'ایمان'],
['Whole (Of)', 'Kol', 'کل'],
['Ambience', 'Safaa', 'صفا'],
['Education', 'Tahseelaat', 'تحصیلات'],
['Preference', 'Tarjeeh', 'ترجیح'],
['To Adjust', 'Vafgh Daadan', 'وفق دادن'],
["Don't Worry", 'Negaraan Nabaash', 'نگران نباش'],
['Soil', 'Khaak', 'خاک'],
['Martyr', 'Shaheed', 'شهید'],
['Festivity', 'Ayd', 'عید'],
['Prayer', 'Do-aa', 'دعا'],
['Peace', 'Solh', 'صلح'],
['Amen', 'Aameen', 'امین'],
['Happy', 'Shaad', 'شاد'],
['I Hate', 'Motnaferam', 'متنفرم'],
['Magic', 'Jaadoo', 'جادو'],
];

//  ['', '', ''],
